include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - lib/platform_bridge/pigeon/hardware_api.dart

linter:
  rules:
    always_declare_return_types: true
    avoid_print: true
    prefer_final_locals: true
    require_trailing_commas: true
