// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.flinx.flinx.flinxhardware.bridge

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object HardwareApiPigeonUtils {

  /** 创建通道连接失败时返回给 Flutter 的标准错误对象。 */
  fun createConnectionError(channelName: String): FlutterError {
    return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")  }

  /** 将正常结果按 Pigeon 约定包装为单元素列表。 */
  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  /** 将异常转换为 Pigeon 错误返回结构，优先保留 FlutterError 的字段。 */
  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  /** 比较 Double 是否深度相等：统一 -0.0/0.0，并把 NaN 视为相等。 */
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  /** 比较 Float 是否深度相等：统一 -0.0f/0.0f，并把 NaN 视为相等。 */
  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  /** 计算 Double 的稳定哈希：归一化 -0.0 并保证与 equals 语义一致。 */
  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  /** 计算 Float 的稳定哈希：归一化 -0.0f 并保证与 equals 语义一致。 */
  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  /** 递归比较任意值（数组/列表/映射/浮点等）是否深度相等。 */
  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  /** 递归计算任意值的深度哈希，需与 deepEquals 语义保持一致。 */
  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

enum class PermissionKindDto(val raw: Int) {
  BLUETOOTH(0),
  CAMERA(1),
  LOCAL_NETWORK(2),
  NOTIFICATION(3);

  companion object {
    fun ofRaw(raw: Int): PermissionKindDto? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class DoorCommandDto(val raw: Int) {
  OPEN(0),
  STOP(1),
  CLOSE(2);

  companion object {
    fun ofRaw(raw: Int): DoorCommandDto? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class BleConnectionStateDto(val raw: Int) {
  DISCONNECTED(0),
  CONNECTING(1),
  CONNECTED(2);

  companion object {
    fun ofRaw(raw: Int): BleConnectionStateDto? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class BleWriteTypeDto(val raw: Int) {
  WITH_RESPONSE(0),
  WITHOUT_RESPONSE(1);

  companion object {
    fun ofRaw(raw: Int): BleWriteTypeDto? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PermissionSnapshotDto (
  val bluetoothGranted: Boolean,
  val cameraGranted: Boolean,
  val localNetworkGranted: Boolean,
  val notificationGranted: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PermissionSnapshotDto {
      val bluetoothGranted = pigeonVar_list[0] as Boolean
      val cameraGranted = pigeonVar_list[1] as Boolean
      val localNetworkGranted = pigeonVar_list[2] as Boolean
      val notificationGranted = pigeonVar_list[3] as Boolean
      return PermissionSnapshotDto(bluetoothGranted, cameraGranted, localNetworkGranted, notificationGranted)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      bluetoothGranted,
      cameraGranted,
      localNetworkGranted,
      notificationGranted,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as PermissionSnapshotDto
    return HardwareApiPigeonUtils.deepEquals(this.bluetoothGranted, other.bluetoothGranted) && HardwareApiPigeonUtils.deepEquals(this.cameraGranted, other.cameraGranted) && HardwareApiPigeonUtils.deepEquals(this.localNetworkGranted, other.localNetworkGranted) && HardwareApiPigeonUtils.deepEquals(this.notificationGranted, other.notificationGranted)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.bluetoothGranted)
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.cameraGranted)
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.localNetworkGranted)
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.notificationGranted)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class BleScanFilterDto (
  val serviceUuids: List<String>,
  val namePrefix: String? = null,
  val exactName: String? = null,
  val allowDuplicates: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): BleScanFilterDto {
      val serviceUuids = pigeonVar_list[0] as List<String>
      val namePrefix = pigeonVar_list[1] as String?
      val exactName = pigeonVar_list[2] as String?
      val allowDuplicates = pigeonVar_list[3] as Boolean
      return BleScanFilterDto(serviceUuids, namePrefix, exactName, allowDuplicates)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      serviceUuids,
      namePrefix,
      exactName,
      allowDuplicates,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as BleScanFilterDto
    return HardwareApiPigeonUtils.deepEquals(this.serviceUuids, other.serviceUuids) && HardwareApiPigeonUtils.deepEquals(this.namePrefix, other.namePrefix) && HardwareApiPigeonUtils.deepEquals(this.exactName, other.exactName) && HardwareApiPigeonUtils.deepEquals(this.allowDuplicates, other.allowDuplicates)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.serviceUuids)
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.namePrefix)
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.exactName)
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.allowDuplicates)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class BleDeviceDto (
  val requestId: String,
  val scanSessionId: String,
  val id: String,
  val name: String? = null,
  val rssi: Long,
  val advertisementServiceUuids: List<String>,
  val manufacturerData: ByteArray,
  val seenAtMillis: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): BleDeviceDto {
      val requestId = pigeonVar_list[0] as String
      val scanSessionId = pigeonVar_list[1] as String
      val id = pigeonVar_list[2] as String
      val name = pigeonVar_list[3] as String?
      val rssi = pigeonVar_list[4] as Long
      val advertisementServiceUuids = pigeonVar_list[5] as List<String>
      val manufacturerData = pigeonVar_list[6] as ByteArray
      val seenAtMillis = pigeonVar_list[7] as Long
      return BleDeviceDto(requestId, scanSessionId, id, name, rssi, advertisementServiceUuids, manufacturerData, seenAtMillis)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      requestId,
      scanSessionId,
      id,
      name,
      rssi,
      advertisementServiceUuids,
      manufacturerData,
      seenAtMillis,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as BleDeviceDto
    return HardwareApiPigeonUtils.deepEquals(this.requestId, other.requestId) && HardwareApiPigeonUtils.deepEquals(this.scanSessionId, other.scanSessionId) && HardwareApiPigeonUtils.deepEquals(this.id, other.id) && HardwareApiPigeonUtils.deepEquals(this.name, other.name) && HardwareApiPigeonUtils.deepEquals(this.rssi, other.rssi) && HardwareApiPigeonUtils.deepEquals(this.advertisementServiceUuids, other.advertisementServiceUuids) && HardwareApiPigeonUtils.deepEquals(this.manufacturerData, other.manufacturerData) && HardwareApiPigeonUtils.deepEquals(this.seenAtMillis, other.seenAtMillis)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.requestId)
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.scanSessionId)
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.id)
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.name)
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.rssi)
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.advertisementServiceUuids)
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.manufacturerData)
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.seenAtMillis)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class BleConnectionEventDto (
  val requestId: String,
  val deviceId: String,
  val state: BleConnectionStateDto,
  val nativeCode: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): BleConnectionEventDto {
      val requestId = pigeonVar_list[0] as String
      val deviceId = pigeonVar_list[1] as String
      val state = pigeonVar_list[2] as BleConnectionStateDto
      val nativeCode = pigeonVar_list[3] as String?
      return BleConnectionEventDto(requestId, deviceId, state, nativeCode)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      requestId,
      deviceId,
      state,
      nativeCode,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as BleConnectionEventDto
    return HardwareApiPigeonUtils.deepEquals(this.requestId, other.requestId) && HardwareApiPigeonUtils.deepEquals(this.deviceId, other.deviceId) && HardwareApiPigeonUtils.deepEquals(this.state, other.state) && HardwareApiPigeonUtils.deepEquals(this.nativeCode, other.nativeCode)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.requestId)
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.deviceId)
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.state)
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.nativeCode)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class BleCharacteristicDto (
  val serviceUuid: String,
  val characteristicUuid: String,
  val canRead: Boolean,
  val canWriteWithResponse: Boolean,
  val canWriteWithoutResponse: Boolean,
  val canNotify: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): BleCharacteristicDto {
      val serviceUuid = pigeonVar_list[0] as String
      val characteristicUuid = pigeonVar_list[1] as String
      val canRead = pigeonVar_list[2] as Boolean
      val canWriteWithResponse = pigeonVar_list[3] as Boolean
      val canWriteWithoutResponse = pigeonVar_list[4] as Boolean
      val canNotify = pigeonVar_list[5] as Boolean
      return BleCharacteristicDto(serviceUuid, characteristicUuid, canRead, canWriteWithResponse, canWriteWithoutResponse, canNotify)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      serviceUuid,
      characteristicUuid,
      canRead,
      canWriteWithResponse,
      canWriteWithoutResponse,
      canNotify,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as BleCharacteristicDto
    return HardwareApiPigeonUtils.deepEquals(this.serviceUuid, other.serviceUuid) && HardwareApiPigeonUtils.deepEquals(this.characteristicUuid, other.characteristicUuid) && HardwareApiPigeonUtils.deepEquals(this.canRead, other.canRead) && HardwareApiPigeonUtils.deepEquals(this.canWriteWithResponse, other.canWriteWithResponse) && HardwareApiPigeonUtils.deepEquals(this.canWriteWithoutResponse, other.canWriteWithoutResponse) && HardwareApiPigeonUtils.deepEquals(this.canNotify, other.canNotify)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.serviceUuid)
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.characteristicUuid)
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.canRead)
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.canWriteWithResponse)
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.canWriteWithoutResponse)
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.canNotify)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class BleServiceDto (
  val serviceUuid: String,
  val characteristics: List<BleCharacteristicDto>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): BleServiceDto {
      val serviceUuid = pigeonVar_list[0] as String
      val characteristics = pigeonVar_list[1] as List<BleCharacteristicDto>
      return BleServiceDto(serviceUuid, characteristics)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      serviceUuid,
      characteristics,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as BleServiceDto
    return HardwareApiPigeonUtils.deepEquals(this.serviceUuid, other.serviceUuid) && HardwareApiPigeonUtils.deepEquals(this.characteristics, other.characteristics)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.serviceUuid)
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.characteristics)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class BleServicesDto (
  val requestId: String,
  val deviceId: String,
  val services: List<BleServiceDto>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): BleServicesDto {
      val requestId = pigeonVar_list[0] as String
      val deviceId = pigeonVar_list[1] as String
      val services = pigeonVar_list[2] as List<BleServiceDto>
      return BleServicesDto(requestId, deviceId, services)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      requestId,
      deviceId,
      services,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as BleServicesDto
    return HardwareApiPigeonUtils.deepEquals(this.requestId, other.requestId) && HardwareApiPigeonUtils.deepEquals(this.deviceId, other.deviceId) && HardwareApiPigeonUtils.deepEquals(this.services, other.services)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.requestId)
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.deviceId)
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.services)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class BleReadResultDto (
  val requestId: String,
  val deviceId: String,
  val serviceUuid: String,
  val characteristicUuid: String,
  val payload: ByteArray
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): BleReadResultDto {
      val requestId = pigeonVar_list[0] as String
      val deviceId = pigeonVar_list[1] as String
      val serviceUuid = pigeonVar_list[2] as String
      val characteristicUuid = pigeonVar_list[3] as String
      val payload = pigeonVar_list[4] as ByteArray
      return BleReadResultDto(requestId, deviceId, serviceUuid, characteristicUuid, payload)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      requestId,
      deviceId,
      serviceUuid,
      characteristicUuid,
      payload,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as BleReadResultDto
    return HardwareApiPigeonUtils.deepEquals(this.requestId, other.requestId) && HardwareApiPigeonUtils.deepEquals(this.deviceId, other.deviceId) && HardwareApiPigeonUtils.deepEquals(this.serviceUuid, other.serviceUuid) && HardwareApiPigeonUtils.deepEquals(this.characteristicUuid, other.characteristicUuid) && HardwareApiPigeonUtils.deepEquals(this.payload, other.payload)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.requestId)
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.deviceId)
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.serviceUuid)
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.characteristicUuid)
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.payload)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class BleWriteResultDto (
  val requestId: String,
  val deviceId: String,
  val serviceUuid: String,
  val characteristicUuid: String,
  val accepted: Boolean,
  val nativeCode: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): BleWriteResultDto {
      val requestId = pigeonVar_list[0] as String
      val deviceId = pigeonVar_list[1] as String
      val serviceUuid = pigeonVar_list[2] as String
      val characteristicUuid = pigeonVar_list[3] as String
      val accepted = pigeonVar_list[4] as Boolean
      val nativeCode = pigeonVar_list[5] as String?
      return BleWriteResultDto(requestId, deviceId, serviceUuid, characteristicUuid, accepted, nativeCode)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      requestId,
      deviceId,
      serviceUuid,
      characteristicUuid,
      accepted,
      nativeCode,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as BleWriteResultDto
    return HardwareApiPigeonUtils.deepEquals(this.requestId, other.requestId) && HardwareApiPigeonUtils.deepEquals(this.deviceId, other.deviceId) && HardwareApiPigeonUtils.deepEquals(this.serviceUuid, other.serviceUuid) && HardwareApiPigeonUtils.deepEquals(this.characteristicUuid, other.characteristicUuid) && HardwareApiPigeonUtils.deepEquals(this.accepted, other.accepted) && HardwareApiPigeonUtils.deepEquals(this.nativeCode, other.nativeCode)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.requestId)
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.deviceId)
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.serviceUuid)
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.characteristicUuid)
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.accepted)
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.nativeCode)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class BleNotificationDto (
  val requestId: String? = null,
  val deviceId: String,
  val serviceUuid: String,
  val characteristicUuid: String,
  val payload: ByteArray,
  val timestampMillis: Long,
  val sequenceNumber: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): BleNotificationDto {
      val requestId = pigeonVar_list[0] as String?
      val deviceId = pigeonVar_list[1] as String
      val serviceUuid = pigeonVar_list[2] as String
      val characteristicUuid = pigeonVar_list[3] as String
      val payload = pigeonVar_list[4] as ByteArray
      val timestampMillis = pigeonVar_list[5] as Long
      val sequenceNumber = pigeonVar_list[6] as Long
      return BleNotificationDto(requestId, deviceId, serviceUuid, characteristicUuid, payload, timestampMillis, sequenceNumber)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      requestId,
      deviceId,
      serviceUuid,
      characteristicUuid,
      payload,
      timestampMillis,
      sequenceNumber,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as BleNotificationDto
    return HardwareApiPigeonUtils.deepEquals(this.requestId, other.requestId) && HardwareApiPigeonUtils.deepEquals(this.deviceId, other.deviceId) && HardwareApiPigeonUtils.deepEquals(this.serviceUuid, other.serviceUuid) && HardwareApiPigeonUtils.deepEquals(this.characteristicUuid, other.characteristicUuid) && HardwareApiPigeonUtils.deepEquals(this.payload, other.payload) && HardwareApiPigeonUtils.deepEquals(this.timestampMillis, other.timestampMillis) && HardwareApiPigeonUtils.deepEquals(this.sequenceNumber, other.sequenceNumber)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.requestId)
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.deviceId)
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.serviceUuid)
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.characteristicUuid)
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.payload)
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.timestampMillis)
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.sequenceNumber)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class NativeErrorDto (
  val code: String,
  val domainCode: String,
  val message: String? = null,
  val requestId: String? = null,
  val deviceId: String? = null,
  val retryable: Boolean,
  val timestampMillis: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeErrorDto {
      val code = pigeonVar_list[0] as String
      val domainCode = pigeonVar_list[1] as String
      val message = pigeonVar_list[2] as String?
      val requestId = pigeonVar_list[3] as String?
      val deviceId = pigeonVar_list[4] as String?
      val retryable = pigeonVar_list[5] as Boolean
      val timestampMillis = pigeonVar_list[6] as Long
      return NativeErrorDto(code, domainCode, message, requestId, deviceId, retryable, timestampMillis)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      code,
      domainCode,
      message,
      requestId,
      deviceId,
      retryable,
      timestampMillis,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as NativeErrorDto
    return HardwareApiPigeonUtils.deepEquals(this.code, other.code) && HardwareApiPigeonUtils.deepEquals(this.domainCode, other.domainCode) && HardwareApiPigeonUtils.deepEquals(this.message, other.message) && HardwareApiPigeonUtils.deepEquals(this.requestId, other.requestId) && HardwareApiPigeonUtils.deepEquals(this.deviceId, other.deviceId) && HardwareApiPigeonUtils.deepEquals(this.retryable, other.retryable) && HardwareApiPigeonUtils.deepEquals(this.timestampMillis, other.timestampMillis)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.code)
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.domainCode)
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.message)
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.requestId)
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.deviceId)
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.retryable)
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.timestampMillis)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class CommandResultDto (
  val requestId: String,
  val deviceId: String,
  val accepted: Boolean,
  val nativeCode: String? = null,
  val domainCode: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): CommandResultDto {
      val requestId = pigeonVar_list[0] as String
      val deviceId = pigeonVar_list[1] as String
      val accepted = pigeonVar_list[2] as Boolean
      val nativeCode = pigeonVar_list[3] as String?
      val domainCode = pigeonVar_list[4] as String?
      return CommandResultDto(requestId, deviceId, accepted, nativeCode, domainCode)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      requestId,
      deviceId,
      accepted,
      nativeCode,
      domainCode,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as CommandResultDto
    return HardwareApiPigeonUtils.deepEquals(this.requestId, other.requestId) && HardwareApiPigeonUtils.deepEquals(this.deviceId, other.deviceId) && HardwareApiPigeonUtils.deepEquals(this.accepted, other.accepted) && HardwareApiPigeonUtils.deepEquals(this.nativeCode, other.nativeCode) && HardwareApiPigeonUtils.deepEquals(this.domainCode, other.domainCode)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.requestId)
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.deviceId)
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.accepted)
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.nativeCode)
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.domainCode)
    return result
  }
}
private open class HardwareApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          PermissionKindDto.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          DoorCommandDto.ofRaw(it.toInt())
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          BleConnectionStateDto.ofRaw(it.toInt())
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          BleWriteTypeDto.ofRaw(it.toInt())
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PermissionSnapshotDto.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          BleScanFilterDto.fromList(it)
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          BleDeviceDto.fromList(it)
        }
      }
      136.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          BleConnectionEventDto.fromList(it)
        }
      }
      137.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          BleCharacteristicDto.fromList(it)
        }
      }
      138.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          BleServiceDto.fromList(it)
        }
      }
      139.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          BleServicesDto.fromList(it)
        }
      }
      140.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          BleReadResultDto.fromList(it)
        }
      }
      141.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          BleWriteResultDto.fromList(it)
        }
      }
      142.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          BleNotificationDto.fromList(it)
        }
      }
      143.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeErrorDto.fromList(it)
        }
      }
      144.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CommandResultDto.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is PermissionKindDto -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is DoorCommandDto -> {
        stream.write(130)
        writeValue(stream, value.raw.toLong())
      }
      is BleConnectionStateDto -> {
        stream.write(131)
        writeValue(stream, value.raw.toLong())
      }
      is BleWriteTypeDto -> {
        stream.write(132)
        writeValue(stream, value.raw.toLong())
      }
      is PermissionSnapshotDto -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is BleScanFilterDto -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      is BleDeviceDto -> {
        stream.write(135)
        writeValue(stream, value.toList())
      }
      is BleConnectionEventDto -> {
        stream.write(136)
        writeValue(stream, value.toList())
      }
      is BleCharacteristicDto -> {
        stream.write(137)
        writeValue(stream, value.toList())
      }
      is BleServiceDto -> {
        stream.write(138)
        writeValue(stream, value.toList())
      }
      is BleServicesDto -> {
        stream.write(139)
        writeValue(stream, value.toList())
      }
      is BleReadResultDto -> {
        stream.write(140)
        writeValue(stream, value.toList())
      }
      is BleWriteResultDto -> {
        stream.write(141)
        writeValue(stream, value.toList())
      }
      is BleNotificationDto -> {
        stream.write(142)
        writeValue(stream, value.toList())
      }
      is NativeErrorDto -> {
        stream.write(143)
        writeValue(stream, value.toList())
      }
      is CommandResultDto -> {
        stream.write(144)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface HardwareHostApi {
  fun getPermissionSnapshot(): PermissionSnapshotDto
  fun requestPermissions(permissions: List<PermissionKindDto>): PermissionSnapshotDto
  fun startBleScan(requestId: String, filter: BleScanFilterDto)
  fun stopBleScan(requestId: String)
  fun connectBleDevice(requestId: String, deviceId: String, callback: (Result<BleConnectionEventDto>) -> Unit)
  fun disconnectBleDevice(requestId: String, deviceId: String, callback: (Result<BleConnectionEventDto>) -> Unit)
  fun discoverServices(requestId: String, deviceId: String, callback: (Result<BleServicesDto>) -> Unit)
  fun readCharacteristic(requestId: String, deviceId: String, serviceUuid: String, characteristicUuid: String, callback: (Result<BleReadResultDto>) -> Unit)
  fun writeCharacteristic(requestId: String, deviceId: String, serviceUuid: String, characteristicUuid: String, payload: ByteArray, writeType: BleWriteTypeDto, callback: (Result<BleWriteResultDto>) -> Unit)
  fun setCharacteristicNotify(requestId: String, deviceId: String, serviceUuid: String, characteristicUuid: String, enabled: Boolean, callback: (Result<BleWriteResultDto>) -> Unit)
  fun sendDoorCommand(requestId: String, deviceId: String, command: DoorCommandDto): CommandResultDto

  companion object {
    /** The codec used by HardwareHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      HardwareApiPigeonCodec()
    }
    /** Sets up an instance of `HardwareHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: HardwareHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flinx.HardwareHostApi.getPermissionSnapshot$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getPermissionSnapshot())
            } catch (exception: Throwable) {
              HardwareApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flinx.HardwareHostApi.requestPermissions$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val permissionsArg = args[0] as List<PermissionKindDto>
            val wrapped: List<Any?> = try {
              listOf(api.requestPermissions(permissionsArg))
            } catch (exception: Throwable) {
              HardwareApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flinx.HardwareHostApi.startBleScan$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestIdArg = args[0] as String
            val filterArg = args[1] as BleScanFilterDto
            val wrapped: List<Any?> = try {
              api.startBleScan(requestIdArg, filterArg)
              listOf(null)
            } catch (exception: Throwable) {
              HardwareApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flinx.HardwareHostApi.stopBleScan$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestIdArg = args[0] as String
            val wrapped: List<Any?> = try {
              api.stopBleScan(requestIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              HardwareApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flinx.HardwareHostApi.connectBleDevice$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestIdArg = args[0] as String
            val deviceIdArg = args[1] as String
            api.connectBleDevice(requestIdArg, deviceIdArg) { result: Result<BleConnectionEventDto> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(HardwareApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(HardwareApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flinx.HardwareHostApi.disconnectBleDevice$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestIdArg = args[0] as String
            val deviceIdArg = args[1] as String
            api.disconnectBleDevice(requestIdArg, deviceIdArg) { result: Result<BleConnectionEventDto> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(HardwareApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(HardwareApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flinx.HardwareHostApi.discoverServices$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestIdArg = args[0] as String
            val deviceIdArg = args[1] as String
            api.discoverServices(requestIdArg, deviceIdArg) { result: Result<BleServicesDto> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(HardwareApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(HardwareApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flinx.HardwareHostApi.readCharacteristic$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestIdArg = args[0] as String
            val deviceIdArg = args[1] as String
            val serviceUuidArg = args[2] as String
            val characteristicUuidArg = args[3] as String
            api.readCharacteristic(requestIdArg, deviceIdArg, serviceUuidArg, characteristicUuidArg) { result: Result<BleReadResultDto> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(HardwareApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(HardwareApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flinx.HardwareHostApi.writeCharacteristic$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestIdArg = args[0] as String
            val deviceIdArg = args[1] as String
            val serviceUuidArg = args[2] as String
            val characteristicUuidArg = args[3] as String
            val payloadArg = args[4] as ByteArray
            val writeTypeArg = args[5] as BleWriteTypeDto
            api.writeCharacteristic(requestIdArg, deviceIdArg, serviceUuidArg, characteristicUuidArg, payloadArg, writeTypeArg) { result: Result<BleWriteResultDto> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(HardwareApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(HardwareApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flinx.HardwareHostApi.setCharacteristicNotify$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestIdArg = args[0] as String
            val deviceIdArg = args[1] as String
            val serviceUuidArg = args[2] as String
            val characteristicUuidArg = args[3] as String
            val enabledArg = args[4] as Boolean
            api.setCharacteristicNotify(requestIdArg, deviceIdArg, serviceUuidArg, characteristicUuidArg, enabledArg) { result: Result<BleWriteResultDto> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(HardwareApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(HardwareApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flinx.HardwareHostApi.sendDoorCommand$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestIdArg = args[0] as String
            val deviceIdArg = args[1] as String
            val commandArg = args[2] as DoorCommandDto
            val wrapped: List<Any?> = try {
              listOf(api.sendDoorCommand(requestIdArg, deviceIdArg, commandArg))
            } catch (exception: Throwable) {
              HardwareApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
class HardwareFlutterApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by HardwareFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      HardwareApiPigeonCodec()
    }
  }
  fun onBleScanResult(deviceArg: BleDeviceDto, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.flinx.HardwareFlutterApi.onBleScanResult$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(deviceArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(HardwareApiPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onBleConnectionChanged(eventArg: BleConnectionEventDto, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.flinx.HardwareFlutterApi.onBleConnectionChanged$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(eventArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(HardwareApiPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onBleNotification(notificationArg: BleNotificationDto, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.flinx.HardwareFlutterApi.onBleNotification$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(notificationArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(HardwareApiPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onNativeError(errorArg: NativeErrorDto, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.flinx.HardwareFlutterApi.onNativeError$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(errorArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(HardwareApiPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
}
