// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.flinx.flinx.flinxhardware.bridge

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object HardwareApiPigeonUtils {

  fun createConnectionError(channelName: String): FlutterError {
    return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")  }

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

enum class PermissionKindDto(val raw: Int) {
  BLUETOOTH(0),
  CAMERA(1),
  LOCATION(2),
  MICROPHONE(3),
  STORAGE(4),
  LOCAL_NETWORK(5),
  NOTIFICATION(6);

  companion object {
    fun ofRaw(raw: Int): PermissionKindDto? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class PermissionStatusDto(val raw: Int) {
  GRANTED(0),
  DENIED(1),
  BLOCKED(2);

  companion object {
    fun ofRaw(raw: Int): PermissionStatusDto? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class DoorCommandDto(val raw: Int) {
  OPEN(0),
  STOP(1),
  CLOSE(2),
  PARTIAL_OPEN(3),
  LIGHT_ON(4),
  LIGHT_OFF(5),
  PB(6);

  companion object {
    fun ofRaw(raw: Int): DoorCommandDto? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class RemotePairingActionDto(val raw: Int) {
  START(0),
  CANCEL(1);

  companion object {
    fun ofRaw(raw: Int): RemotePairingActionDto? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class RemotePairingStatusDto(val raw: Int) {
  SUCCESS(0),
  FAILURE(1),
  TIMEOUT(2),
  UNKNOWN(3);

  companion object {
    fun ofRaw(raw: Int): RemotePairingStatusDto? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class RemoteOperationStatusDto(val raw: Int) {
  SUCCESS(0),
  FAILURE(1),
  UNKNOWN(2);

  companion object {
    fun ofRaw(raw: Int): RemoteOperationStatusDto? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class BleConnectionStateDto(val raw: Int) {
  DISCONNECTED(0),
  CONNECTING(1),
  CONNECTED(2);

  companion object {
    fun ofRaw(raw: Int): BleConnectionStateDto? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class BleWriteTypeDto(val raw: Int) {
  WITH_RESPONSE(0),
  WITHOUT_RESPONSE(1);

  companion object {
    fun ofRaw(raw: Int): BleWriteTypeDto? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class BleDiagnosticDirectionDto(val raw: Int) {
  TX(0),
  RX(1);

  companion object {
    fun ofRaw(raw: Int): BleDiagnosticDirectionDto? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PermissionSnapshotDto (
  val bluetoothStatus: PermissionStatusDto,
  val cameraStatus: PermissionStatusDto,
  val locationStatus: PermissionStatusDto,
  val microphoneStatus: PermissionStatusDto,
  val storageStatus: PermissionStatusDto,
  val localNetworkGranted: Boolean,
  val notificationGranted: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PermissionSnapshotDto {
      val bluetoothStatus = pigeonVar_list[0] as PermissionStatusDto
      val cameraStatus = pigeonVar_list[1] as PermissionStatusDto
      val locationStatus = pigeonVar_list[2] as PermissionStatusDto
      val microphoneStatus = pigeonVar_list[3] as PermissionStatusDto
      val storageStatus = pigeonVar_list[4] as PermissionStatusDto
      val localNetworkGranted = pigeonVar_list[5] as Boolean
      val notificationGranted = pigeonVar_list[6] as Boolean
      return PermissionSnapshotDto(bluetoothStatus, cameraStatus, locationStatus, microphoneStatus, storageStatus, localNetworkGranted, notificationGranted)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      bluetoothStatus,
      cameraStatus,
      locationStatus,
      microphoneStatus,
      storageStatus,
      localNetworkGranted,
      notificationGranted,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as PermissionSnapshotDto
    return HardwareApiPigeonUtils.deepEquals(this.bluetoothStatus, other.bluetoothStatus) && HardwareApiPigeonUtils.deepEquals(this.cameraStatus, other.cameraStatus) && HardwareApiPigeonUtils.deepEquals(this.locationStatus, other.locationStatus) && HardwareApiPigeonUtils.deepEquals(this.microphoneStatus, other.microphoneStatus) && HardwareApiPigeonUtils.deepEquals(this.storageStatus, other.storageStatus) && HardwareApiPigeonUtils.deepEquals(this.localNetworkGranted, other.localNetworkGranted) && HardwareApiPigeonUtils.deepEquals(this.notificationGranted, other.notificationGranted)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.bluetoothStatus)
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.cameraStatus)
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.locationStatus)
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.microphoneStatus)
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.storageStatus)
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.localNetworkGranted)
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.notificationGranted)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class BleScanFilterDto (
  val serviceUuids: List<String>,
  val namePrefix: String? = null,
  val exactName: String? = null,
  val allowDuplicates: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): BleScanFilterDto {
      val serviceUuids = pigeonVar_list[0] as List<String>
      val namePrefix = pigeonVar_list[1] as String?
      val exactName = pigeonVar_list[2] as String?
      val allowDuplicates = pigeonVar_list[3] as Boolean
      return BleScanFilterDto(serviceUuids, namePrefix, exactName, allowDuplicates)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      serviceUuids,
      namePrefix,
      exactName,
      allowDuplicates,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as BleScanFilterDto
    return HardwareApiPigeonUtils.deepEquals(this.serviceUuids, other.serviceUuids) && HardwareApiPigeonUtils.deepEquals(this.namePrefix, other.namePrefix) && HardwareApiPigeonUtils.deepEquals(this.exactName, other.exactName) && HardwareApiPigeonUtils.deepEquals(this.allowDuplicates, other.allowDuplicates)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.serviceUuids)
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.namePrefix)
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.exactName)
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.allowDuplicates)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class BleDeviceDto (
  val requestId: String,
  val scanSessionId: String,
  val id: String,
  val name: String? = null,
  val sn: String? = null,
  val rssi: Long,
  val advertisementServiceUuids: List<String>,
  val manufacturerData: ByteArray,
  val seenAtMillis: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): BleDeviceDto {
      val requestId = pigeonVar_list[0] as String
      val scanSessionId = pigeonVar_list[1] as String
      val id = pigeonVar_list[2] as String
      val name = pigeonVar_list[3] as String?
      val sn = pigeonVar_list[4] as String?
      val rssi = pigeonVar_list[5] as Long
      val advertisementServiceUuids = pigeonVar_list[6] as List<String>
      val manufacturerData = pigeonVar_list[7] as ByteArray
      val seenAtMillis = pigeonVar_list[8] as Long
      return BleDeviceDto(requestId, scanSessionId, id, name, sn, rssi, advertisementServiceUuids, manufacturerData, seenAtMillis)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      requestId,
      scanSessionId,
      id,
      name,
      sn,
      rssi,
      advertisementServiceUuids,
      manufacturerData,
      seenAtMillis,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as BleDeviceDto
    return HardwareApiPigeonUtils.deepEquals(this.requestId, other.requestId) && HardwareApiPigeonUtils.deepEquals(this.scanSessionId, other.scanSessionId) && HardwareApiPigeonUtils.deepEquals(this.id, other.id) && HardwareApiPigeonUtils.deepEquals(this.name, other.name) && HardwareApiPigeonUtils.deepEquals(this.sn, other.sn) && HardwareApiPigeonUtils.deepEquals(this.rssi, other.rssi) && HardwareApiPigeonUtils.deepEquals(this.advertisementServiceUuids, other.advertisementServiceUuids) && HardwareApiPigeonUtils.deepEquals(this.manufacturerData, other.manufacturerData) && HardwareApiPigeonUtils.deepEquals(this.seenAtMillis, other.seenAtMillis)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.requestId)
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.scanSessionId)
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.id)
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.name)
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.sn)
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.rssi)
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.advertisementServiceUuids)
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.manufacturerData)
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.seenAtMillis)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class BleConnectionEventDto (
  val requestId: String,
  val deviceId: String,
  val state: BleConnectionStateDto,
  val nativeCode: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): BleConnectionEventDto {
      val requestId = pigeonVar_list[0] as String
      val deviceId = pigeonVar_list[1] as String
      val state = pigeonVar_list[2] as BleConnectionStateDto
      val nativeCode = pigeonVar_list[3] as String?
      return BleConnectionEventDto(requestId, deviceId, state, nativeCode)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      requestId,
      deviceId,
      state,
      nativeCode,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as BleConnectionEventDto
    return HardwareApiPigeonUtils.deepEquals(this.requestId, other.requestId) && HardwareApiPigeonUtils.deepEquals(this.deviceId, other.deviceId) && HardwareApiPigeonUtils.deepEquals(this.state, other.state) && HardwareApiPigeonUtils.deepEquals(this.nativeCode, other.nativeCode)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.requestId)
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.deviceId)
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.state)
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.nativeCode)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class BleAuthenticationResultDto (
  val requestId: String,
  val deviceId: String,
  val authenticated: Boolean,
  val bindingState: Long? = null,
  val nativeCode: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): BleAuthenticationResultDto {
      val requestId = pigeonVar_list[0] as String
      val deviceId = pigeonVar_list[1] as String
      val authenticated = pigeonVar_list[2] as Boolean
      val bindingState = pigeonVar_list[3] as Long?
      val nativeCode = pigeonVar_list[4] as String?
      return BleAuthenticationResultDto(requestId, deviceId, authenticated, bindingState, nativeCode)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      requestId,
      deviceId,
      authenticated,
      bindingState,
      nativeCode,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as BleAuthenticationResultDto
    return HardwareApiPigeonUtils.deepEquals(this.requestId, other.requestId) && HardwareApiPigeonUtils.deepEquals(this.deviceId, other.deviceId) && HardwareApiPigeonUtils.deepEquals(this.authenticated, other.authenticated) && HardwareApiPigeonUtils.deepEquals(this.bindingState, other.bindingState) && HardwareApiPigeonUtils.deepEquals(this.nativeCode, other.nativeCode)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.requestId)
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.deviceId)
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.authenticated)
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.bindingState)
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.nativeCode)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class WifiScanResultDto (
  val requestId: String,
  val deviceId: String,
  val ssids: List<String>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): WifiScanResultDto {
      val requestId = pigeonVar_list[0] as String
      val deviceId = pigeonVar_list[1] as String
      val ssids = pigeonVar_list[2] as List<String>
      return WifiScanResultDto(requestId, deviceId, ssids)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      requestId,
      deviceId,
      ssids,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as WifiScanResultDto
    return HardwareApiPigeonUtils.deepEquals(this.requestId, other.requestId) && HardwareApiPigeonUtils.deepEquals(this.deviceId, other.deviceId) && HardwareApiPigeonUtils.deepEquals(this.ssids, other.ssids)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.requestId)
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.deviceId)
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.ssids)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class WifiProvisionResultDto (
  val requestId: String,
  val deviceId: String,
  val ssid: String,
  val success: Boolean,
  val nativeCode: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): WifiProvisionResultDto {
      val requestId = pigeonVar_list[0] as String
      val deviceId = pigeonVar_list[1] as String
      val ssid = pigeonVar_list[2] as String
      val success = pigeonVar_list[3] as Boolean
      val nativeCode = pigeonVar_list[4] as String?
      return WifiProvisionResultDto(requestId, deviceId, ssid, success, nativeCode)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      requestId,
      deviceId,
      ssid,
      success,
      nativeCode,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as WifiProvisionResultDto
    return HardwareApiPigeonUtils.deepEquals(this.requestId, other.requestId) && HardwareApiPigeonUtils.deepEquals(this.deviceId, other.deviceId) && HardwareApiPigeonUtils.deepEquals(this.ssid, other.ssid) && HardwareApiPigeonUtils.deepEquals(this.success, other.success) && HardwareApiPigeonUtils.deepEquals(this.nativeCode, other.nativeCode)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.requestId)
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.deviceId)
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.ssid)
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.success)
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.nativeCode)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class BleCharacteristicDto (
  val serviceUuid: String,
  val characteristicUuid: String,
  val canRead: Boolean,
  val canWriteWithResponse: Boolean,
  val canWriteWithoutResponse: Boolean,
  val canNotify: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): BleCharacteristicDto {
      val serviceUuid = pigeonVar_list[0] as String
      val characteristicUuid = pigeonVar_list[1] as String
      val canRead = pigeonVar_list[2] as Boolean
      val canWriteWithResponse = pigeonVar_list[3] as Boolean
      val canWriteWithoutResponse = pigeonVar_list[4] as Boolean
      val canNotify = pigeonVar_list[5] as Boolean
      return BleCharacteristicDto(serviceUuid, characteristicUuid, canRead, canWriteWithResponse, canWriteWithoutResponse, canNotify)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      serviceUuid,
      characteristicUuid,
      canRead,
      canWriteWithResponse,
      canWriteWithoutResponse,
      canNotify,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as BleCharacteristicDto
    return HardwareApiPigeonUtils.deepEquals(this.serviceUuid, other.serviceUuid) && HardwareApiPigeonUtils.deepEquals(this.characteristicUuid, other.characteristicUuid) && HardwareApiPigeonUtils.deepEquals(this.canRead, other.canRead) && HardwareApiPigeonUtils.deepEquals(this.canWriteWithResponse, other.canWriteWithResponse) && HardwareApiPigeonUtils.deepEquals(this.canWriteWithoutResponse, other.canWriteWithoutResponse) && HardwareApiPigeonUtils.deepEquals(this.canNotify, other.canNotify)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.serviceUuid)
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.characteristicUuid)
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.canRead)
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.canWriteWithResponse)
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.canWriteWithoutResponse)
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.canNotify)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class BleServiceDto (
  val serviceUuid: String,
  val characteristics: List<BleCharacteristicDto>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): BleServiceDto {
      val serviceUuid = pigeonVar_list[0] as String
      val characteristics = pigeonVar_list[1] as List<BleCharacteristicDto>
      return BleServiceDto(serviceUuid, characteristics)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      serviceUuid,
      characteristics,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as BleServiceDto
    return HardwareApiPigeonUtils.deepEquals(this.serviceUuid, other.serviceUuid) && HardwareApiPigeonUtils.deepEquals(this.characteristics, other.characteristics)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.serviceUuid)
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.characteristics)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class BleServicesDto (
  val requestId: String,
  val deviceId: String,
  val services: List<BleServiceDto>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): BleServicesDto {
      val requestId = pigeonVar_list[0] as String
      val deviceId = pigeonVar_list[1] as String
      val services = pigeonVar_list[2] as List<BleServiceDto>
      return BleServicesDto(requestId, deviceId, services)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      requestId,
      deviceId,
      services,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as BleServicesDto
    return HardwareApiPigeonUtils.deepEquals(this.requestId, other.requestId) && HardwareApiPigeonUtils.deepEquals(this.deviceId, other.deviceId) && HardwareApiPigeonUtils.deepEquals(this.services, other.services)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.requestId)
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.deviceId)
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.services)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class BleReadResultDto (
  val requestId: String,
  val deviceId: String,
  val serviceUuid: String,
  val characteristicUuid: String,
  val payload: ByteArray
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): BleReadResultDto {
      val requestId = pigeonVar_list[0] as String
      val deviceId = pigeonVar_list[1] as String
      val serviceUuid = pigeonVar_list[2] as String
      val characteristicUuid = pigeonVar_list[3] as String
      val payload = pigeonVar_list[4] as ByteArray
      return BleReadResultDto(requestId, deviceId, serviceUuid, characteristicUuid, payload)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      requestId,
      deviceId,
      serviceUuid,
      characteristicUuid,
      payload,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as BleReadResultDto
    return HardwareApiPigeonUtils.deepEquals(this.requestId, other.requestId) && HardwareApiPigeonUtils.deepEquals(this.deviceId, other.deviceId) && HardwareApiPigeonUtils.deepEquals(this.serviceUuid, other.serviceUuid) && HardwareApiPigeonUtils.deepEquals(this.characteristicUuid, other.characteristicUuid) && HardwareApiPigeonUtils.deepEquals(this.payload, other.payload)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.requestId)
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.deviceId)
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.serviceUuid)
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.characteristicUuid)
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.payload)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class BleWriteResultDto (
  val requestId: String,
  val deviceId: String,
  val serviceUuid: String,
  val characteristicUuid: String,
  val accepted: Boolean,
  val nativeCode: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): BleWriteResultDto {
      val requestId = pigeonVar_list[0] as String
      val deviceId = pigeonVar_list[1] as String
      val serviceUuid = pigeonVar_list[2] as String
      val characteristicUuid = pigeonVar_list[3] as String
      val accepted = pigeonVar_list[4] as Boolean
      val nativeCode = pigeonVar_list[5] as String?
      return BleWriteResultDto(requestId, deviceId, serviceUuid, characteristicUuid, accepted, nativeCode)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      requestId,
      deviceId,
      serviceUuid,
      characteristicUuid,
      accepted,
      nativeCode,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as BleWriteResultDto
    return HardwareApiPigeonUtils.deepEquals(this.requestId, other.requestId) && HardwareApiPigeonUtils.deepEquals(this.deviceId, other.deviceId) && HardwareApiPigeonUtils.deepEquals(this.serviceUuid, other.serviceUuid) && HardwareApiPigeonUtils.deepEquals(this.characteristicUuid, other.characteristicUuid) && HardwareApiPigeonUtils.deepEquals(this.accepted, other.accepted) && HardwareApiPigeonUtils.deepEquals(this.nativeCode, other.nativeCode)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.requestId)
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.deviceId)
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.serviceUuid)
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.characteristicUuid)
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.accepted)
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.nativeCode)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class BleNotificationDto (
  val requestId: String? = null,
  val deviceId: String,
  val serviceUuid: String,
  val characteristicUuid: String,
  val payload: ByteArray,
  val timestampMillis: Long,
  val sequenceNumber: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): BleNotificationDto {
      val requestId = pigeonVar_list[0] as String?
      val deviceId = pigeonVar_list[1] as String
      val serviceUuid = pigeonVar_list[2] as String
      val characteristicUuid = pigeonVar_list[3] as String
      val payload = pigeonVar_list[4] as ByteArray
      val timestampMillis = pigeonVar_list[5] as Long
      val sequenceNumber = pigeonVar_list[6] as Long
      return BleNotificationDto(requestId, deviceId, serviceUuid, characteristicUuid, payload, timestampMillis, sequenceNumber)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      requestId,
      deviceId,
      serviceUuid,
      characteristicUuid,
      payload,
      timestampMillis,
      sequenceNumber,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as BleNotificationDto
    return HardwareApiPigeonUtils.deepEquals(this.requestId, other.requestId) && HardwareApiPigeonUtils.deepEquals(this.deviceId, other.deviceId) && HardwareApiPigeonUtils.deepEquals(this.serviceUuid, other.serviceUuid) && HardwareApiPigeonUtils.deepEquals(this.characteristicUuid, other.characteristicUuid) && HardwareApiPigeonUtils.deepEquals(this.payload, other.payload) && HardwareApiPigeonUtils.deepEquals(this.timestampMillis, other.timestampMillis) && HardwareApiPigeonUtils.deepEquals(this.sequenceNumber, other.sequenceNumber)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.requestId)
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.deviceId)
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.serviceUuid)
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.characteristicUuid)
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.payload)
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.timestampMillis)
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.sequenceNumber)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class NativeErrorDto (
  val code: String,
  val domainCode: String,
  val message: String? = null,
  val requestId: String? = null,
  val deviceId: String? = null,
  val retryable: Boolean,
  val timestampMillis: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeErrorDto {
      val code = pigeonVar_list[0] as String
      val domainCode = pigeonVar_list[1] as String
      val message = pigeonVar_list[2] as String?
      val requestId = pigeonVar_list[3] as String?
      val deviceId = pigeonVar_list[4] as String?
      val retryable = pigeonVar_list[5] as Boolean
      val timestampMillis = pigeonVar_list[6] as Long
      return NativeErrorDto(code, domainCode, message, requestId, deviceId, retryable, timestampMillis)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      code,
      domainCode,
      message,
      requestId,
      deviceId,
      retryable,
      timestampMillis,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as NativeErrorDto
    return HardwareApiPigeonUtils.deepEquals(this.code, other.code) && HardwareApiPigeonUtils.deepEquals(this.domainCode, other.domainCode) && HardwareApiPigeonUtils.deepEquals(this.message, other.message) && HardwareApiPigeonUtils.deepEquals(this.requestId, other.requestId) && HardwareApiPigeonUtils.deepEquals(this.deviceId, other.deviceId) && HardwareApiPigeonUtils.deepEquals(this.retryable, other.retryable) && HardwareApiPigeonUtils.deepEquals(this.timestampMillis, other.timestampMillis)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.code)
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.domainCode)
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.message)
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.requestId)
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.deviceId)
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.retryable)
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.timestampMillis)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class BleDiagnosticEventDto (
  val direction: BleDiagnosticDirectionDto,
  val timestampMillis: Long,
  val transactionId: String,
  val requestId: String? = null,
  val deviceId: String,
  val operation: String,
  val command: Long,
  val control: Long? = null,
  val sequence: Long,
  val encryption: String,
  val originPayload: ByteArray,
  val encryptedPayload: ByteArray,
  val decryptedPayload: ByteArray,
  val packet: ByteArray,
  val elapsedMillis: Long? = null,
  val result: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): BleDiagnosticEventDto {
      val direction = pigeonVar_list[0] as BleDiagnosticDirectionDto
      val timestampMillis = pigeonVar_list[1] as Long
      val transactionId = pigeonVar_list[2] as String
      val requestId = pigeonVar_list[3] as String?
      val deviceId = pigeonVar_list[4] as String
      val operation = pigeonVar_list[5] as String
      val command = pigeonVar_list[6] as Long
      val control = pigeonVar_list[7] as Long?
      val sequence = pigeonVar_list[8] as Long
      val encryption = pigeonVar_list[9] as String
      val originPayload = pigeonVar_list[10] as ByteArray
      val encryptedPayload = pigeonVar_list[11] as ByteArray
      val decryptedPayload = pigeonVar_list[12] as ByteArray
      val packet = pigeonVar_list[13] as ByteArray
      val elapsedMillis = pigeonVar_list[14] as Long?
      val result = pigeonVar_list[15] as String?
      return BleDiagnosticEventDto(direction, timestampMillis, transactionId, requestId, deviceId, operation, command, control, sequence, encryption, originPayload, encryptedPayload, decryptedPayload, packet, elapsedMillis, result)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      direction,
      timestampMillis,
      transactionId,
      requestId,
      deviceId,
      operation,
      command,
      control,
      sequence,
      encryption,
      originPayload,
      encryptedPayload,
      decryptedPayload,
      packet,
      elapsedMillis,
      result,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as BleDiagnosticEventDto
    return HardwareApiPigeonUtils.deepEquals(this.direction, other.direction) && HardwareApiPigeonUtils.deepEquals(this.timestampMillis, other.timestampMillis) && HardwareApiPigeonUtils.deepEquals(this.transactionId, other.transactionId) && HardwareApiPigeonUtils.deepEquals(this.requestId, other.requestId) && HardwareApiPigeonUtils.deepEquals(this.deviceId, other.deviceId) && HardwareApiPigeonUtils.deepEquals(this.operation, other.operation) && HardwareApiPigeonUtils.deepEquals(this.command, other.command) && HardwareApiPigeonUtils.deepEquals(this.control, other.control) && HardwareApiPigeonUtils.deepEquals(this.sequence, other.sequence) && HardwareApiPigeonUtils.deepEquals(this.encryption, other.encryption) && HardwareApiPigeonUtils.deepEquals(this.originPayload, other.originPayload) && HardwareApiPigeonUtils.deepEquals(this.encryptedPayload, other.encryptedPayload) && HardwareApiPigeonUtils.deepEquals(this.decryptedPayload, other.decryptedPayload) && HardwareApiPigeonUtils.deepEquals(this.packet, other.packet) && HardwareApiPigeonUtils.deepEquals(this.elapsedMillis, other.elapsedMillis) && HardwareApiPigeonUtils.deepEquals(this.result, other.result)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.direction)
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.timestampMillis)
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.transactionId)
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.requestId)
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.deviceId)
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.operation)
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.command)
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.control)
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.sequence)
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.encryption)
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.originPayload)
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.encryptedPayload)
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.decryptedPayload)
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.packet)
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.elapsedMillis)
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.result)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class CommandResultDto (
  val requestId: String,
  val deviceId: String,
  val accepted: Boolean,
  val nativeCode: String? = null,
  val domainCode: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): CommandResultDto {
      val requestId = pigeonVar_list[0] as String
      val deviceId = pigeonVar_list[1] as String
      val accepted = pigeonVar_list[2] as Boolean
      val nativeCode = pigeonVar_list[3] as String?
      val domainCode = pigeonVar_list[4] as String?
      return CommandResultDto(requestId, deviceId, accepted, nativeCode, domainCode)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      requestId,
      deviceId,
      accepted,
      nativeCode,
      domainCode,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as CommandResultDto
    return HardwareApiPigeonUtils.deepEquals(this.requestId, other.requestId) && HardwareApiPigeonUtils.deepEquals(this.deviceId, other.deviceId) && HardwareApiPigeonUtils.deepEquals(this.accepted, other.accepted) && HardwareApiPigeonUtils.deepEquals(this.nativeCode, other.nativeCode) && HardwareApiPigeonUtils.deepEquals(this.domainCode, other.domainCode)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.requestId)
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.deviceId)
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.accepted)
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.nativeCode)
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.domainCode)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class RemotePairingResultDto (
  val requestId: String,
  val deviceId: String,
  val status: RemotePairingStatusDto,
  val reasonCode: Long,
  val nativeCode: String? = null,
  val domainCode: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): RemotePairingResultDto {
      val requestId = pigeonVar_list[0] as String
      val deviceId = pigeonVar_list[1] as String
      val status = pigeonVar_list[2] as RemotePairingStatusDto
      val reasonCode = pigeonVar_list[3] as Long
      val nativeCode = pigeonVar_list[4] as String?
      val domainCode = pigeonVar_list[5] as String?
      return RemotePairingResultDto(requestId, deviceId, status, reasonCode, nativeCode, domainCode)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      requestId,
      deviceId,
      status,
      reasonCode,
      nativeCode,
      domainCode,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as RemotePairingResultDto
    return HardwareApiPigeonUtils.deepEquals(this.requestId, other.requestId) && HardwareApiPigeonUtils.deepEquals(this.deviceId, other.deviceId) && HardwareApiPigeonUtils.deepEquals(this.status, other.status) && HardwareApiPigeonUtils.deepEquals(this.reasonCode, other.reasonCode) && HardwareApiPigeonUtils.deepEquals(this.nativeCode, other.nativeCode) && HardwareApiPigeonUtils.deepEquals(this.domainCode, other.domainCode)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.requestId)
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.deviceId)
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.status)
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.reasonCode)
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.nativeCode)
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.domainCode)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class RemoteControlDto (
  val name: String,
  val serialNumber: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): RemoteControlDto {
      val name = pigeonVar_list[0] as String
      val serialNumber = pigeonVar_list[1] as Long
      return RemoteControlDto(name, serialNumber)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      name,
      serialNumber,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as RemoteControlDto
    return HardwareApiPigeonUtils.deepEquals(this.name, other.name) && HardwareApiPigeonUtils.deepEquals(this.serialNumber, other.serialNumber)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.name)
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.serialNumber)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class RemoteControlListResultDto (
  val requestId: String,
  val deviceId: String,
  val totalCount: Long,
  val totalPages: Long,
  val currentPage: Long,
  val hasMore: Boolean,
  val remotes: List<RemoteControlDto>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): RemoteControlListResultDto {
      val requestId = pigeonVar_list[0] as String
      val deviceId = pigeonVar_list[1] as String
      val totalCount = pigeonVar_list[2] as Long
      val totalPages = pigeonVar_list[3] as Long
      val currentPage = pigeonVar_list[4] as Long
      val hasMore = pigeonVar_list[5] as Boolean
      val remotes = pigeonVar_list[6] as List<RemoteControlDto>
      return RemoteControlListResultDto(requestId, deviceId, totalCount, totalPages, currentPage, hasMore, remotes)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      requestId,
      deviceId,
      totalCount,
      totalPages,
      currentPage,
      hasMore,
      remotes,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as RemoteControlListResultDto
    return HardwareApiPigeonUtils.deepEquals(this.requestId, other.requestId) && HardwareApiPigeonUtils.deepEquals(this.deviceId, other.deviceId) && HardwareApiPigeonUtils.deepEquals(this.totalCount, other.totalCount) && HardwareApiPigeonUtils.deepEquals(this.totalPages, other.totalPages) && HardwareApiPigeonUtils.deepEquals(this.currentPage, other.currentPage) && HardwareApiPigeonUtils.deepEquals(this.hasMore, other.hasMore) && HardwareApiPigeonUtils.deepEquals(this.remotes, other.remotes)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.requestId)
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.deviceId)
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.totalCount)
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.totalPages)
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.currentPage)
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.hasMore)
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.remotes)
    return result
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class RemoteOperationResultDto (
  val requestId: String,
  val deviceId: String,
  val status: RemoteOperationStatusDto,
  val reasonCode: Long,
  val nativeCode: String? = null,
  val domainCode: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): RemoteOperationResultDto {
      val requestId = pigeonVar_list[0] as String
      val deviceId = pigeonVar_list[1] as String
      val status = pigeonVar_list[2] as RemoteOperationStatusDto
      val reasonCode = pigeonVar_list[3] as Long
      val nativeCode = pigeonVar_list[4] as String?
      val domainCode = pigeonVar_list[5] as String?
      return RemoteOperationResultDto(requestId, deviceId, status, reasonCode, nativeCode, domainCode)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      requestId,
      deviceId,
      status,
      reasonCode,
      nativeCode,
      domainCode,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as RemoteOperationResultDto
    return HardwareApiPigeonUtils.deepEquals(this.requestId, other.requestId) && HardwareApiPigeonUtils.deepEquals(this.deviceId, other.deviceId) && HardwareApiPigeonUtils.deepEquals(this.status, other.status) && HardwareApiPigeonUtils.deepEquals(this.reasonCode, other.reasonCode) && HardwareApiPigeonUtils.deepEquals(this.nativeCode, other.nativeCode) && HardwareApiPigeonUtils.deepEquals(this.domainCode, other.domainCode)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.requestId)
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.deviceId)
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.status)
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.reasonCode)
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.nativeCode)
    result = 31 * result + HardwareApiPigeonUtils.deepHash(this.domainCode)
    return result
  }
}
private open class HardwareApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          PermissionKindDto.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          PermissionStatusDto.ofRaw(it.toInt())
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          DoorCommandDto.ofRaw(it.toInt())
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          RemotePairingActionDto.ofRaw(it.toInt())
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          RemotePairingStatusDto.ofRaw(it.toInt())
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          RemoteOperationStatusDto.ofRaw(it.toInt())
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          BleConnectionStateDto.ofRaw(it.toInt())
        }
      }
      136.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          BleWriteTypeDto.ofRaw(it.toInt())
        }
      }
      137.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          BleDiagnosticDirectionDto.ofRaw(it.toInt())
        }
      }
      138.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PermissionSnapshotDto.fromList(it)
        }
      }
      139.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          BleScanFilterDto.fromList(it)
        }
      }
      140.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          BleDeviceDto.fromList(it)
        }
      }
      141.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          BleConnectionEventDto.fromList(it)
        }
      }
      142.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          BleAuthenticationResultDto.fromList(it)
        }
      }
      143.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          WifiScanResultDto.fromList(it)
        }
      }
      144.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          WifiProvisionResultDto.fromList(it)
        }
      }
      145.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          BleCharacteristicDto.fromList(it)
        }
      }
      146.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          BleServiceDto.fromList(it)
        }
      }
      147.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          BleServicesDto.fromList(it)
        }
      }
      148.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          BleReadResultDto.fromList(it)
        }
      }
      149.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          BleWriteResultDto.fromList(it)
        }
      }
      150.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          BleNotificationDto.fromList(it)
        }
      }
      151.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeErrorDto.fromList(it)
        }
      }
      152.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          BleDiagnosticEventDto.fromList(it)
        }
      }
      153.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          CommandResultDto.fromList(it)
        }
      }
      154.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          RemotePairingResultDto.fromList(it)
        }
      }
      155.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          RemoteControlDto.fromList(it)
        }
      }
      156.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          RemoteControlListResultDto.fromList(it)
        }
      }
      157.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          RemoteOperationResultDto.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is PermissionKindDto -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is PermissionStatusDto -> {
        stream.write(130)
        writeValue(stream, value.raw.toLong())
      }
      is DoorCommandDto -> {
        stream.write(131)
        writeValue(stream, value.raw.toLong())
      }
      is RemotePairingActionDto -> {
        stream.write(132)
        writeValue(stream, value.raw.toLong())
      }
      is RemotePairingStatusDto -> {
        stream.write(133)
        writeValue(stream, value.raw.toLong())
      }
      is RemoteOperationStatusDto -> {
        stream.write(134)
        writeValue(stream, value.raw.toLong())
      }
      is BleConnectionStateDto -> {
        stream.write(135)
        writeValue(stream, value.raw.toLong())
      }
      is BleWriteTypeDto -> {
        stream.write(136)
        writeValue(stream, value.raw.toLong())
      }
      is BleDiagnosticDirectionDto -> {
        stream.write(137)
        writeValue(stream, value.raw.toLong())
      }
      is PermissionSnapshotDto -> {
        stream.write(138)
        writeValue(stream, value.toList())
      }
      is BleScanFilterDto -> {
        stream.write(139)
        writeValue(stream, value.toList())
      }
      is BleDeviceDto -> {
        stream.write(140)
        writeValue(stream, value.toList())
      }
      is BleConnectionEventDto -> {
        stream.write(141)
        writeValue(stream, value.toList())
      }
      is BleAuthenticationResultDto -> {
        stream.write(142)
        writeValue(stream, value.toList())
      }
      is WifiScanResultDto -> {
        stream.write(143)
        writeValue(stream, value.toList())
      }
      is WifiProvisionResultDto -> {
        stream.write(144)
        writeValue(stream, value.toList())
      }
      is BleCharacteristicDto -> {
        stream.write(145)
        writeValue(stream, value.toList())
      }
      is BleServiceDto -> {
        stream.write(146)
        writeValue(stream, value.toList())
      }
      is BleServicesDto -> {
        stream.write(147)
        writeValue(stream, value.toList())
      }
      is BleReadResultDto -> {
        stream.write(148)
        writeValue(stream, value.toList())
      }
      is BleWriteResultDto -> {
        stream.write(149)
        writeValue(stream, value.toList())
      }
      is BleNotificationDto -> {
        stream.write(150)
        writeValue(stream, value.toList())
      }
      is NativeErrorDto -> {
        stream.write(151)
        writeValue(stream, value.toList())
      }
      is BleDiagnosticEventDto -> {
        stream.write(152)
        writeValue(stream, value.toList())
      }
      is CommandResultDto -> {
        stream.write(153)
        writeValue(stream, value.toList())
      }
      is RemotePairingResultDto -> {
        stream.write(154)
        writeValue(stream, value.toList())
      }
      is RemoteControlDto -> {
        stream.write(155)
        writeValue(stream, value.toList())
      }
      is RemoteControlListResultDto -> {
        stream.write(156)
        writeValue(stream, value.toList())
      }
      is RemoteOperationResultDto -> {
        stream.write(157)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface HardwareHostApi {
  fun configureHardwareLogging(flutterConsoleEnabled: Boolean, nativeConsoleEnabled: Boolean)
  fun getPermissionSnapshot(requestId: String): PermissionSnapshotDto
  fun requestPermissions(requestId: String, permissions: List<PermissionKindDto>): PermissionSnapshotDto
  fun openAppSettings(requestId: String)
  fun startBleScan(requestId: String, filter: BleScanFilterDto)
  fun stopBleScan(requestId: String)
  fun connectBleDevice(requestId: String, deviceId: String, callback: (Result<BleConnectionEventDto>) -> Unit)
  fun authenticateBleDevice(requestId: String, deviceId: String, token: String, aesKey: String, aesKeyVersion: String, callback: (Result<BleAuthenticationResultDto>) -> Unit)
  fun scanWifiNetworks(requestId: String, deviceId: String, callback: (Result<WifiScanResultDto>) -> Unit)
  fun configureWifi(requestId: String, deviceId: String, ssid: String, password: String, callback: (Result<WifiProvisionResultDto>) -> Unit)
  fun disconnectBleDevice(requestId: String, deviceId: String, callback: (Result<BleConnectionEventDto>) -> Unit)
  fun discoverServices(requestId: String, deviceId: String, callback: (Result<BleServicesDto>) -> Unit)
  fun readCharacteristic(requestId: String, deviceId: String, serviceUuid: String, characteristicUuid: String, callback: (Result<BleReadResultDto>) -> Unit)
  fun writeCharacteristic(requestId: String, deviceId: String, serviceUuid: String, characteristicUuid: String, payload: ByteArray, writeType: BleWriteTypeDto, callback: (Result<BleWriteResultDto>) -> Unit)
  fun setCharacteristicNotify(requestId: String, deviceId: String, serviceUuid: String, characteristicUuid: String, enabled: Boolean, callback: (Result<BleWriteResultDto>) -> Unit)
  fun sendDoorCommand(requestId: String, deviceId: String, command: DoorCommandDto, callback: (Result<CommandResultDto>) -> Unit)
  fun pairRemote(requestId: String, deviceId: String, action: RemotePairingActionDto, callback: (Result<RemotePairingResultDto>) -> Unit)
  fun queryRemotes(requestId: String, deviceId: String, callback: (Result<RemoteControlListResultDto>) -> Unit)
  fun deleteRemote(requestId: String, deviceId: String, serialNumber: Long?, callback: (Result<RemoteOperationResultDto>) -> Unit)
  fun renameRemote(requestId: String, deviceId: String, serialNumber: Long, name: String, callback: (Result<RemoteOperationResultDto>) -> Unit)

  companion object {
    /** The codec used by HardwareHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      HardwareApiPigeonCodec()
    }
    /** Sets up an instance of `HardwareHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: HardwareHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flinx.HardwareHostApi.configureHardwareLogging$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val flutterConsoleEnabledArg = args[0] as Boolean
            val nativeConsoleEnabledArg = args[1] as Boolean
            val wrapped: List<Any?> = try {
              api.configureHardwareLogging(flutterConsoleEnabledArg, nativeConsoleEnabledArg)
              listOf(null)
            } catch (exception: Throwable) {
              HardwareApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flinx.HardwareHostApi.getPermissionSnapshot$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestIdArg = args[0] as String
            val wrapped: List<Any?> = try {
              listOf(api.getPermissionSnapshot(requestIdArg))
            } catch (exception: Throwable) {
              HardwareApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flinx.HardwareHostApi.requestPermissions$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestIdArg = args[0] as String
            val permissionsArg = args[1] as List<PermissionKindDto>
            val wrapped: List<Any?> = try {
              listOf(api.requestPermissions(requestIdArg, permissionsArg))
            } catch (exception: Throwable) {
              HardwareApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flinx.HardwareHostApi.openAppSettings$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestIdArg = args[0] as String
            val wrapped: List<Any?> = try {
              api.openAppSettings(requestIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              HardwareApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flinx.HardwareHostApi.startBleScan$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestIdArg = args[0] as String
            val filterArg = args[1] as BleScanFilterDto
            val wrapped: List<Any?> = try {
              api.startBleScan(requestIdArg, filterArg)
              listOf(null)
            } catch (exception: Throwable) {
              HardwareApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flinx.HardwareHostApi.stopBleScan$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestIdArg = args[0] as String
            val wrapped: List<Any?> = try {
              api.stopBleScan(requestIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              HardwareApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flinx.HardwareHostApi.connectBleDevice$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestIdArg = args[0] as String
            val deviceIdArg = args[1] as String
            api.connectBleDevice(requestIdArg, deviceIdArg) { result: Result<BleConnectionEventDto> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(HardwareApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(HardwareApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flinx.HardwareHostApi.authenticateBleDevice$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestIdArg = args[0] as String
            val deviceIdArg = args[1] as String
            val tokenArg = args[2] as String
            val aesKeyArg = args[3] as String
            val aesKeyVersionArg = args[4] as String
            api.authenticateBleDevice(requestIdArg, deviceIdArg, tokenArg, aesKeyArg, aesKeyVersionArg) { result: Result<BleAuthenticationResultDto> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(HardwareApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(HardwareApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flinx.HardwareHostApi.scanWifiNetworks$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestIdArg = args[0] as String
            val deviceIdArg = args[1] as String
            api.scanWifiNetworks(requestIdArg, deviceIdArg) { result: Result<WifiScanResultDto> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(HardwareApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(HardwareApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flinx.HardwareHostApi.configureWifi$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestIdArg = args[0] as String
            val deviceIdArg = args[1] as String
            val ssidArg = args[2] as String
            val passwordArg = args[3] as String
            api.configureWifi(requestIdArg, deviceIdArg, ssidArg, passwordArg) { result: Result<WifiProvisionResultDto> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(HardwareApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(HardwareApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flinx.HardwareHostApi.disconnectBleDevice$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestIdArg = args[0] as String
            val deviceIdArg = args[1] as String
            api.disconnectBleDevice(requestIdArg, deviceIdArg) { result: Result<BleConnectionEventDto> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(HardwareApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(HardwareApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flinx.HardwareHostApi.discoverServices$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestIdArg = args[0] as String
            val deviceIdArg = args[1] as String
            api.discoverServices(requestIdArg, deviceIdArg) { result: Result<BleServicesDto> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(HardwareApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(HardwareApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flinx.HardwareHostApi.readCharacteristic$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestIdArg = args[0] as String
            val deviceIdArg = args[1] as String
            val serviceUuidArg = args[2] as String
            val characteristicUuidArg = args[3] as String
            api.readCharacteristic(requestIdArg, deviceIdArg, serviceUuidArg, characteristicUuidArg) { result: Result<BleReadResultDto> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(HardwareApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(HardwareApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flinx.HardwareHostApi.writeCharacteristic$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestIdArg = args[0] as String
            val deviceIdArg = args[1] as String
            val serviceUuidArg = args[2] as String
            val characteristicUuidArg = args[3] as String
            val payloadArg = args[4] as ByteArray
            val writeTypeArg = args[5] as BleWriteTypeDto
            api.writeCharacteristic(requestIdArg, deviceIdArg, serviceUuidArg, characteristicUuidArg, payloadArg, writeTypeArg) { result: Result<BleWriteResultDto> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(HardwareApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(HardwareApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flinx.HardwareHostApi.setCharacteristicNotify$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestIdArg = args[0] as String
            val deviceIdArg = args[1] as String
            val serviceUuidArg = args[2] as String
            val characteristicUuidArg = args[3] as String
            val enabledArg = args[4] as Boolean
            api.setCharacteristicNotify(requestIdArg, deviceIdArg, serviceUuidArg, characteristicUuidArg, enabledArg) { result: Result<BleWriteResultDto> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(HardwareApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(HardwareApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flinx.HardwareHostApi.sendDoorCommand$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestIdArg = args[0] as String
            val deviceIdArg = args[1] as String
            val commandArg = args[2] as DoorCommandDto
            api.sendDoorCommand(requestIdArg, deviceIdArg, commandArg) { result: Result<CommandResultDto> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(HardwareApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(HardwareApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flinx.HardwareHostApi.pairRemote$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestIdArg = args[0] as String
            val deviceIdArg = args[1] as String
            val actionArg = args[2] as RemotePairingActionDto
            api.pairRemote(requestIdArg, deviceIdArg, actionArg) { result: Result<RemotePairingResultDto> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(HardwareApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(HardwareApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flinx.HardwareHostApi.queryRemotes$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestIdArg = args[0] as String
            val deviceIdArg = args[1] as String
            api.queryRemotes(requestIdArg, deviceIdArg) { result: Result<RemoteControlListResultDto> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(HardwareApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(HardwareApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flinx.HardwareHostApi.deleteRemote$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestIdArg = args[0] as String
            val deviceIdArg = args[1] as String
            val serialNumberArg = args[2] as Long?
            api.deleteRemote(requestIdArg, deviceIdArg, serialNumberArg) { result: Result<RemoteOperationResultDto> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(HardwareApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(HardwareApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flinx.HardwareHostApi.renameRemote$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestIdArg = args[0] as String
            val deviceIdArg = args[1] as String
            val serialNumberArg = args[2] as Long
            val nameArg = args[3] as String
            api.renameRemote(requestIdArg, deviceIdArg, serialNumberArg, nameArg) { result: Result<RemoteOperationResultDto> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(HardwareApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(HardwareApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
class HardwareFlutterApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by HardwareFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      HardwareApiPigeonCodec()
    }
  }
  fun onBleScanResult(deviceArg: BleDeviceDto, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.flinx.HardwareFlutterApi.onBleScanResult$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(deviceArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(HardwareApiPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onBleConnectionChanged(eventArg: BleConnectionEventDto, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.flinx.HardwareFlutterApi.onBleConnectionChanged$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(eventArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(HardwareApiPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onBleNotification(notificationArg: BleNotificationDto, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.flinx.HardwareFlutterApi.onBleNotification$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(notificationArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(HardwareApiPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onNativeError(errorArg: NativeErrorDto, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.flinx.HardwareFlutterApi.onNativeError$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(errorArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(HardwareApiPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
  fun onBleDiagnosticEvent(eventArg: BleDiagnosticEventDto, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.flinx.HardwareFlutterApi.onBleDiagnosticEvent$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(eventArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(HardwareApiPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
}
