// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

private func doubleEqualsHardwareApi(_ lhs: Double, _ rhs: Double) -> Bool {
  return (lhs.isNaN && rhs.isNaN) || lhs == rhs
}

private func doubleHashHardwareApi(_ value: Double, _ hasher: inout Hasher) {
  if value.isNaN {
    hasher.combine(0x7FF8000000000000)
  } else {
    // Normalize -0.0 to 0.0
    hasher.combine(value == 0 ? 0 : value)
  }
}

func deepEqualsHardwareApi(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
    return true

  case is (Void, Void):
    return true

  case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
    guard lhsArray.count == rhsArray.count else { return false }
    for (index, element) in lhsArray.enumerated() {
      if !deepEqualsHardwareApi(element, rhsArray[index]) {
        return false
      }
    }
    return true

  case (let lhsArray, let rhsArray) as ([Double], [Double]):
    guard lhsArray.count == rhsArray.count else { return false }
    for (index, element) in lhsArray.enumerated() {
      if !doubleEqualsHardwareApi(element, rhsArray[index]) {
        return false
      }
    }
    return true

  case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard lhsDictionary.count == rhsDictionary.count else { return false }
    for (lhsKey, lhsValue) in lhsDictionary {
      var found = false
      for (rhsKey, rhsValue) in rhsDictionary {
        if deepEqualsHardwareApi(lhsKey, rhsKey) {
          if deepEqualsHardwareApi(lhsValue, rhsValue) {
            found = true
            break
          } else {
            return false
          }
        }
      }
      if !found { return false }
    }
    return true

  case (let lhs as Double, let rhs as Double):
    return doubleEqualsHardwareApi(lhs, rhs)

  case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
    return lhsHashable == rhsHashable

  default:
    return false
  }
}

func deepHashHardwareApi(value: Any?, hasher: inout Hasher) {
  let cleanValue = nilOrValue(value) as Any?
  if let cleanValue = cleanValue {
    if let doubleValue = cleanValue as? Double {
      doubleHashHardwareApi(doubleValue, &hasher)
    } else if let valueList = cleanValue as? [Any?] {
      for item in valueList {
        deepHashHardwareApi(value: item, hasher: &hasher)
      }
    } else if let valueList = cleanValue as? [Double] {
      for item in valueList {
        doubleHashHardwareApi(item, &hasher)
      }
    } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
      var result = 0
      for (key, value) in valueDict {
        var entryKeyHasher = Hasher()
        deepHashHardwareApi(value: key, hasher: &entryKeyHasher)
        var entryValueHasher = Hasher()
        deepHashHardwareApi(value: value, hasher: &entryValueHasher)
        result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
      }
      hasher.combine(result)
    } else if let hashableValue = cleanValue as? AnyHashable {
      hasher.combine(hashableValue)
    } else {
      hasher.combine(String(describing: cleanValue))
    }
  } else {
    hasher.combine(0)
  }
}


enum PermissionKindDto: Int {
  case bluetooth = 0
  case camera = 1
  case localNetwork = 2
  case notification = 3
}

enum DoorCommandDto: Int {
  case open = 0
  case stop = 1
  case close = 2
}

/// Generated class from Pigeon that represents data sent in messages.
struct PermissionSnapshotDto: Hashable {
  var bluetoothGranted: Bool
  var cameraGranted: Bool
  var localNetworkGranted: Bool
  var notificationGranted: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PermissionSnapshotDto? {
    let bluetoothGranted = pigeonVar_list[0] as! Bool
    let cameraGranted = pigeonVar_list[1] as! Bool
    let localNetworkGranted = pigeonVar_list[2] as! Bool
    let notificationGranted = pigeonVar_list[3] as! Bool

    return PermissionSnapshotDto(
      bluetoothGranted: bluetoothGranted,
      cameraGranted: cameraGranted,
      localNetworkGranted: localNetworkGranted,
      notificationGranted: notificationGranted
    )
  }
  func toList() -> [Any?] {
    return [
      bluetoothGranted,
      cameraGranted,
      localNetworkGranted,
      notificationGranted,
    ]
  }
  static func == (lhs: PermissionSnapshotDto, rhs: PermissionSnapshotDto) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsHardwareApi(lhs.bluetoothGranted, rhs.bluetoothGranted) && deepEqualsHardwareApi(lhs.cameraGranted, rhs.cameraGranted) && deepEqualsHardwareApi(lhs.localNetworkGranted, rhs.localNetworkGranted) && deepEqualsHardwareApi(lhs.notificationGranted, rhs.notificationGranted)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PermissionSnapshotDto")
    deepHashHardwareApi(value: bluetoothGranted, hasher: &hasher)
    deepHashHardwareApi(value: cameraGranted, hasher: &hasher)
    deepHashHardwareApi(value: localNetworkGranted, hasher: &hasher)
    deepHashHardwareApi(value: notificationGranted, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct CommandResultDto: Hashable {
  var requestId: String
  var deviceId: String
  var accepted: Bool
  var nativeCode: String? = nil
  var domainCode: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> CommandResultDto? {
    let requestId = pigeonVar_list[0] as! String
    let deviceId = pigeonVar_list[1] as! String
    let accepted = pigeonVar_list[2] as! Bool
    let nativeCode: String? = nilOrValue(pigeonVar_list[3])
    let domainCode: String? = nilOrValue(pigeonVar_list[4])

    return CommandResultDto(
      requestId: requestId,
      deviceId: deviceId,
      accepted: accepted,
      nativeCode: nativeCode,
      domainCode: domainCode
    )
  }
  func toList() -> [Any?] {
    return [
      requestId,
      deviceId,
      accepted,
      nativeCode,
      domainCode,
    ]
  }
  static func == (lhs: CommandResultDto, rhs: CommandResultDto) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsHardwareApi(lhs.requestId, rhs.requestId) && deepEqualsHardwareApi(lhs.deviceId, rhs.deviceId) && deepEqualsHardwareApi(lhs.accepted, rhs.accepted) && deepEqualsHardwareApi(lhs.nativeCode, rhs.nativeCode) && deepEqualsHardwareApi(lhs.domainCode, rhs.domainCode)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("CommandResultDto")
    deepHashHardwareApi(value: requestId, hasher: &hasher)
    deepHashHardwareApi(value: deviceId, hasher: &hasher)
    deepHashHardwareApi(value: accepted, hasher: &hasher)
    deepHashHardwareApi(value: nativeCode, hasher: &hasher)
    deepHashHardwareApi(value: domainCode, hasher: &hasher)
  }
}

private class HardwareApiPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return PermissionKindDto(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return DoorCommandDto(rawValue: enumResultAsInt)
      }
      return nil
    case 131:
      return PermissionSnapshotDto.fromList(self.readValue() as! [Any?])
    case 132:
      return CommandResultDto.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class HardwareApiPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? PermissionKindDto {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? DoorCommandDto {
      super.writeByte(130)
      super.writeValue(value.rawValue)
    } else if let value = value as? PermissionSnapshotDto {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? CommandResultDto {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class HardwareApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return HardwareApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return HardwareApiPigeonCodecWriter(data: data)
  }
}

class HardwareApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = HardwareApiPigeonCodec(readerWriter: HardwareApiPigeonCodecReaderWriter())
}

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol HardwareHostApi {
  func getPermissionSnapshot() throws -> PermissionSnapshotDto
  func requestPermissions(permissions: [PermissionKindDto]) throws -> PermissionSnapshotDto
  func sendDoorCommand(requestId: String, deviceId: String, command: DoorCommandDto) throws -> CommandResultDto
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class HardwareHostApiSetup {
  static var codec: FlutterStandardMessageCodec { HardwareApiPigeonCodec.shared }
  /// Sets up an instance of `HardwareHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: HardwareHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let getPermissionSnapshotChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flinx.HardwareHostApi.getPermissionSnapshot\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getPermissionSnapshotChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getPermissionSnapshot()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getPermissionSnapshotChannel.setMessageHandler(nil)
    }
    let requestPermissionsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flinx.HardwareHostApi.requestPermissions\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      requestPermissionsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let permissionsArg = args[0] as! [PermissionKindDto]
        do {
          let result = try api.requestPermissions(permissions: permissionsArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      requestPermissionsChannel.setMessageHandler(nil)
    }
    let sendDoorCommandChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flinx.HardwareHostApi.sendDoorCommand\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      sendDoorCommandChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestIdArg = args[0] as! String
        let deviceIdArg = args[1] as! String
        let commandArg = args[2] as! DoorCommandDto
        do {
          let result = try api.sendDoorCommand(requestId: requestIdArg, deviceId: deviceIdArg, command: commandArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      sendDoorCommandChannel.setMessageHandler(nil)
    }
  }
}
