// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

private func doubleEqualsHardwareApi(_ lhs: Double, _ rhs: Double) -> Bool {
  return (lhs.isNaN && rhs.isNaN) || lhs == rhs
}

private func doubleHashHardwareApi(_ value: Double, _ hasher: inout Hasher) {
  if value.isNaN {
    hasher.combine(0x7FF8000000000000)
  } else {
    // Normalize -0.0 to 0.0
    hasher.combine(value == 0 ? 0 : value)
  }
}

func deepEqualsHardwareApi(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
    return true

  case is (Void, Void):
    return true

  case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
    guard lhsArray.count == rhsArray.count else { return false }
    for (index, element) in lhsArray.enumerated() {
      if !deepEqualsHardwareApi(element, rhsArray[index]) {
        return false
      }
    }
    return true

  case (let lhsArray, let rhsArray) as ([Double], [Double]):
    guard lhsArray.count == rhsArray.count else { return false }
    for (index, element) in lhsArray.enumerated() {
      if !doubleEqualsHardwareApi(element, rhsArray[index]) {
        return false
      }
    }
    return true

  case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard lhsDictionary.count == rhsDictionary.count else { return false }
    for (lhsKey, lhsValue) in lhsDictionary {
      var found = false
      for (rhsKey, rhsValue) in rhsDictionary {
        if deepEqualsHardwareApi(lhsKey, rhsKey) {
          if deepEqualsHardwareApi(lhsValue, rhsValue) {
            found = true
            break
          } else {
            return false
          }
        }
      }
      if !found { return false }
    }
    return true

  case (let lhs as Double, let rhs as Double):
    return doubleEqualsHardwareApi(lhs, rhs)

  case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
    return lhsHashable == rhsHashable

  default:
    return false
  }
}

func deepHashHardwareApi(value: Any?, hasher: inout Hasher) {
  let cleanValue = nilOrValue(value) as Any?
  if let cleanValue = cleanValue {
    if let doubleValue = cleanValue as? Double {
      doubleHashHardwareApi(doubleValue, &hasher)
    } else if let valueList = cleanValue as? [Any?] {
      for item in valueList {
        deepHashHardwareApi(value: item, hasher: &hasher)
      }
    } else if let valueList = cleanValue as? [Double] {
      for item in valueList {
        doubleHashHardwareApi(item, &hasher)
      }
    } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
      var result = 0
      for (key, value) in valueDict {
        var entryKeyHasher = Hasher()
        deepHashHardwareApi(value: key, hasher: &entryKeyHasher)
        var entryValueHasher = Hasher()
        deepHashHardwareApi(value: value, hasher: &entryValueHasher)
        result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
      }
      hasher.combine(result)
    } else if let hashableValue = cleanValue as? AnyHashable {
      hasher.combine(hashableValue)
    } else {
      hasher.combine(String(describing: cleanValue))
    }
  } else {
    hasher.combine(0)
  }
}


enum PermissionKindDto: Int {
  case bluetooth = 0
  case camera = 1
  case localNetwork = 2
  case notification = 3
}

enum DoorCommandDto: Int {
  case open = 0
  case stop = 1
  case close = 2
}

enum BleConnectionStateDto: Int {
  case disconnected = 0
  case connecting = 1
  case connected = 2
}

enum BleWriteTypeDto: Int {
  case withResponse = 0
  case withoutResponse = 1
}

/// Generated class from Pigeon that represents data sent in messages.
struct PermissionSnapshotDto: Hashable {
  var bluetoothGranted: Bool
  var cameraGranted: Bool
  var localNetworkGranted: Bool
  var notificationGranted: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PermissionSnapshotDto? {
    let bluetoothGranted = pigeonVar_list[0] as! Bool
    let cameraGranted = pigeonVar_list[1] as! Bool
    let localNetworkGranted = pigeonVar_list[2] as! Bool
    let notificationGranted = pigeonVar_list[3] as! Bool

    return PermissionSnapshotDto(
      bluetoothGranted: bluetoothGranted,
      cameraGranted: cameraGranted,
      localNetworkGranted: localNetworkGranted,
      notificationGranted: notificationGranted
    )
  }
  func toList() -> [Any?] {
    return [
      bluetoothGranted,
      cameraGranted,
      localNetworkGranted,
      notificationGranted,
    ]
  }
  static func == (lhs: PermissionSnapshotDto, rhs: PermissionSnapshotDto) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsHardwareApi(lhs.bluetoothGranted, rhs.bluetoothGranted) && deepEqualsHardwareApi(lhs.cameraGranted, rhs.cameraGranted) && deepEqualsHardwareApi(lhs.localNetworkGranted, rhs.localNetworkGranted) && deepEqualsHardwareApi(lhs.notificationGranted, rhs.notificationGranted)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PermissionSnapshotDto")
    deepHashHardwareApi(value: bluetoothGranted, hasher: &hasher)
    deepHashHardwareApi(value: cameraGranted, hasher: &hasher)
    deepHashHardwareApi(value: localNetworkGranted, hasher: &hasher)
    deepHashHardwareApi(value: notificationGranted, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct BleScanFilterDto: Hashable {
  var serviceUuids: [String]
  var namePrefix: String? = nil
  var exactName: String? = nil
  var allowDuplicates: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> BleScanFilterDto? {
    let serviceUuids = pigeonVar_list[0] as! [String]
    let namePrefix: String? = nilOrValue(pigeonVar_list[1])
    let exactName: String? = nilOrValue(pigeonVar_list[2])
    let allowDuplicates = pigeonVar_list[3] as! Bool

    return BleScanFilterDto(
      serviceUuids: serviceUuids,
      namePrefix: namePrefix,
      exactName: exactName,
      allowDuplicates: allowDuplicates
    )
  }
  func toList() -> [Any?] {
    return [
      serviceUuids,
      namePrefix,
      exactName,
      allowDuplicates,
    ]
  }
  static func == (lhs: BleScanFilterDto, rhs: BleScanFilterDto) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsHardwareApi(lhs.serviceUuids, rhs.serviceUuids) && deepEqualsHardwareApi(lhs.namePrefix, rhs.namePrefix) && deepEqualsHardwareApi(lhs.exactName, rhs.exactName) && deepEqualsHardwareApi(lhs.allowDuplicates, rhs.allowDuplicates)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("BleScanFilterDto")
    deepHashHardwareApi(value: serviceUuids, hasher: &hasher)
    deepHashHardwareApi(value: namePrefix, hasher: &hasher)
    deepHashHardwareApi(value: exactName, hasher: &hasher)
    deepHashHardwareApi(value: allowDuplicates, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct BleDeviceDto: Hashable {
  var requestId: String
  var scanSessionId: String
  var id: String
  var name: String? = nil
  var rssi: Int64
  var advertisementServiceUuids: [String]
  var manufacturerData: FlutterStandardTypedData
  var seenAtMillis: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> BleDeviceDto? {
    let requestId = pigeonVar_list[0] as! String
    let scanSessionId = pigeonVar_list[1] as! String
    let id = pigeonVar_list[2] as! String
    let name: String? = nilOrValue(pigeonVar_list[3])
    let rssi = pigeonVar_list[4] as! Int64
    let advertisementServiceUuids = pigeonVar_list[5] as! [String]
    let manufacturerData = pigeonVar_list[6] as! FlutterStandardTypedData
    let seenAtMillis = pigeonVar_list[7] as! Int64

    return BleDeviceDto(
      requestId: requestId,
      scanSessionId: scanSessionId,
      id: id,
      name: name,
      rssi: rssi,
      advertisementServiceUuids: advertisementServiceUuids,
      manufacturerData: manufacturerData,
      seenAtMillis: seenAtMillis
    )
  }
  func toList() -> [Any?] {
    return [
      requestId,
      scanSessionId,
      id,
      name,
      rssi,
      advertisementServiceUuids,
      manufacturerData,
      seenAtMillis,
    ]
  }
  static func == (lhs: BleDeviceDto, rhs: BleDeviceDto) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsHardwareApi(lhs.requestId, rhs.requestId) && deepEqualsHardwareApi(lhs.scanSessionId, rhs.scanSessionId) && deepEqualsHardwareApi(lhs.id, rhs.id) && deepEqualsHardwareApi(lhs.name, rhs.name) && deepEqualsHardwareApi(lhs.rssi, rhs.rssi) && deepEqualsHardwareApi(lhs.advertisementServiceUuids, rhs.advertisementServiceUuids) && deepEqualsHardwareApi(lhs.manufacturerData, rhs.manufacturerData) && deepEqualsHardwareApi(lhs.seenAtMillis, rhs.seenAtMillis)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("BleDeviceDto")
    deepHashHardwareApi(value: requestId, hasher: &hasher)
    deepHashHardwareApi(value: scanSessionId, hasher: &hasher)
    deepHashHardwareApi(value: id, hasher: &hasher)
    deepHashHardwareApi(value: name, hasher: &hasher)
    deepHashHardwareApi(value: rssi, hasher: &hasher)
    deepHashHardwareApi(value: advertisementServiceUuids, hasher: &hasher)
    deepHashHardwareApi(value: manufacturerData, hasher: &hasher)
    deepHashHardwareApi(value: seenAtMillis, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct BleConnectionEventDto: Hashable {
  var requestId: String
  var deviceId: String
  var state: BleConnectionStateDto
  var nativeCode: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> BleConnectionEventDto? {
    let requestId = pigeonVar_list[0] as! String
    let deviceId = pigeonVar_list[1] as! String
    let state = pigeonVar_list[2] as! BleConnectionStateDto
    let nativeCode: String? = nilOrValue(pigeonVar_list[3])

    return BleConnectionEventDto(
      requestId: requestId,
      deviceId: deviceId,
      state: state,
      nativeCode: nativeCode
    )
  }
  func toList() -> [Any?] {
    return [
      requestId,
      deviceId,
      state,
      nativeCode,
    ]
  }
  static func == (lhs: BleConnectionEventDto, rhs: BleConnectionEventDto) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsHardwareApi(lhs.requestId, rhs.requestId) && deepEqualsHardwareApi(lhs.deviceId, rhs.deviceId) && deepEqualsHardwareApi(lhs.state, rhs.state) && deepEqualsHardwareApi(lhs.nativeCode, rhs.nativeCode)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("BleConnectionEventDto")
    deepHashHardwareApi(value: requestId, hasher: &hasher)
    deepHashHardwareApi(value: deviceId, hasher: &hasher)
    deepHashHardwareApi(value: state, hasher: &hasher)
    deepHashHardwareApi(value: nativeCode, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct BleAuthenticationResultDto: Hashable {
  var requestId: String
  var deviceId: String
  var authenticated: Bool
  var bindingState: Int64? = nil
  var nativeCode: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> BleAuthenticationResultDto? {
    let requestId = pigeonVar_list[0] as! String
    let deviceId = pigeonVar_list[1] as! String
    let authenticated = pigeonVar_list[2] as! Bool
    let bindingState: Int64? = nilOrValue(pigeonVar_list[3])
    let nativeCode: String? = nilOrValue(pigeonVar_list[4])

    return BleAuthenticationResultDto(
      requestId: requestId,
      deviceId: deviceId,
      authenticated: authenticated,
      bindingState: bindingState,
      nativeCode: nativeCode
    )
  }
  func toList() -> [Any?] {
    return [
      requestId,
      deviceId,
      authenticated,
      bindingState,
      nativeCode,
    ]
  }
  static func == (lhs: BleAuthenticationResultDto, rhs: BleAuthenticationResultDto) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsHardwareApi(lhs.requestId, rhs.requestId) && deepEqualsHardwareApi(lhs.deviceId, rhs.deviceId) && deepEqualsHardwareApi(lhs.authenticated, rhs.authenticated) && deepEqualsHardwareApi(lhs.bindingState, rhs.bindingState) && deepEqualsHardwareApi(lhs.nativeCode, rhs.nativeCode)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("BleAuthenticationResultDto")
    deepHashHardwareApi(value: requestId, hasher: &hasher)
    deepHashHardwareApi(value: deviceId, hasher: &hasher)
    deepHashHardwareApi(value: authenticated, hasher: &hasher)
    deepHashHardwareApi(value: bindingState, hasher: &hasher)
    deepHashHardwareApi(value: nativeCode, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct WifiScanResultDto: Hashable {
  var requestId: String
  var deviceId: String
  var ssids: [String]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> WifiScanResultDto? {
    let requestId = pigeonVar_list[0] as! String
    let deviceId = pigeonVar_list[1] as! String
    let ssids = pigeonVar_list[2] as! [String]

    return WifiScanResultDto(
      requestId: requestId,
      deviceId: deviceId,
      ssids: ssids
    )
  }
  func toList() -> [Any?] {
    return [
      requestId,
      deviceId,
      ssids,
    ]
  }
  static func == (lhs: WifiScanResultDto, rhs: WifiScanResultDto) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsHardwareApi(lhs.requestId, rhs.requestId) && deepEqualsHardwareApi(lhs.deviceId, rhs.deviceId) && deepEqualsHardwareApi(lhs.ssids, rhs.ssids)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("WifiScanResultDto")
    deepHashHardwareApi(value: requestId, hasher: &hasher)
    deepHashHardwareApi(value: deviceId, hasher: &hasher)
    deepHashHardwareApi(value: ssids, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct WifiProvisionResultDto: Hashable {
  var requestId: String
  var deviceId: String
  var ssid: String
  var success: Bool
  var nativeCode: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> WifiProvisionResultDto? {
    let requestId = pigeonVar_list[0] as! String
    let deviceId = pigeonVar_list[1] as! String
    let ssid = pigeonVar_list[2] as! String
    let success = pigeonVar_list[3] as! Bool
    let nativeCode: String? = nilOrValue(pigeonVar_list[4])

    return WifiProvisionResultDto(
      requestId: requestId,
      deviceId: deviceId,
      ssid: ssid,
      success: success,
      nativeCode: nativeCode
    )
  }
  func toList() -> [Any?] {
    return [
      requestId,
      deviceId,
      ssid,
      success,
      nativeCode,
    ]
  }
  static func == (lhs: WifiProvisionResultDto, rhs: WifiProvisionResultDto) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsHardwareApi(lhs.requestId, rhs.requestId) && deepEqualsHardwareApi(lhs.deviceId, rhs.deviceId) && deepEqualsHardwareApi(lhs.ssid, rhs.ssid) && deepEqualsHardwareApi(lhs.success, rhs.success) && deepEqualsHardwareApi(lhs.nativeCode, rhs.nativeCode)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("WifiProvisionResultDto")
    deepHashHardwareApi(value: requestId, hasher: &hasher)
    deepHashHardwareApi(value: deviceId, hasher: &hasher)
    deepHashHardwareApi(value: ssid, hasher: &hasher)
    deepHashHardwareApi(value: success, hasher: &hasher)
    deepHashHardwareApi(value: nativeCode, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct BleCharacteristicDto: Hashable {
  var serviceUuid: String
  var characteristicUuid: String
  var canRead: Bool
  var canWriteWithResponse: Bool
  var canWriteWithoutResponse: Bool
  var canNotify: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> BleCharacteristicDto? {
    let serviceUuid = pigeonVar_list[0] as! String
    let characteristicUuid = pigeonVar_list[1] as! String
    let canRead = pigeonVar_list[2] as! Bool
    let canWriteWithResponse = pigeonVar_list[3] as! Bool
    let canWriteWithoutResponse = pigeonVar_list[4] as! Bool
    let canNotify = pigeonVar_list[5] as! Bool

    return BleCharacteristicDto(
      serviceUuid: serviceUuid,
      characteristicUuid: characteristicUuid,
      canRead: canRead,
      canWriteWithResponse: canWriteWithResponse,
      canWriteWithoutResponse: canWriteWithoutResponse,
      canNotify: canNotify
    )
  }
  func toList() -> [Any?] {
    return [
      serviceUuid,
      characteristicUuid,
      canRead,
      canWriteWithResponse,
      canWriteWithoutResponse,
      canNotify,
    ]
  }
  static func == (lhs: BleCharacteristicDto, rhs: BleCharacteristicDto) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsHardwareApi(lhs.serviceUuid, rhs.serviceUuid) && deepEqualsHardwareApi(lhs.characteristicUuid, rhs.characteristicUuid) && deepEqualsHardwareApi(lhs.canRead, rhs.canRead) && deepEqualsHardwareApi(lhs.canWriteWithResponse, rhs.canWriteWithResponse) && deepEqualsHardwareApi(lhs.canWriteWithoutResponse, rhs.canWriteWithoutResponse) && deepEqualsHardwareApi(lhs.canNotify, rhs.canNotify)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("BleCharacteristicDto")
    deepHashHardwareApi(value: serviceUuid, hasher: &hasher)
    deepHashHardwareApi(value: characteristicUuid, hasher: &hasher)
    deepHashHardwareApi(value: canRead, hasher: &hasher)
    deepHashHardwareApi(value: canWriteWithResponse, hasher: &hasher)
    deepHashHardwareApi(value: canWriteWithoutResponse, hasher: &hasher)
    deepHashHardwareApi(value: canNotify, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct BleServiceDto: Hashable {
  var serviceUuid: String
  var characteristics: [BleCharacteristicDto]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> BleServiceDto? {
    let serviceUuid = pigeonVar_list[0] as! String
    let characteristics = pigeonVar_list[1] as! [BleCharacteristicDto]

    return BleServiceDto(
      serviceUuid: serviceUuid,
      characteristics: characteristics
    )
  }
  func toList() -> [Any?] {
    return [
      serviceUuid,
      characteristics,
    ]
  }
  static func == (lhs: BleServiceDto, rhs: BleServiceDto) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsHardwareApi(lhs.serviceUuid, rhs.serviceUuid) && deepEqualsHardwareApi(lhs.characteristics, rhs.characteristics)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("BleServiceDto")
    deepHashHardwareApi(value: serviceUuid, hasher: &hasher)
    deepHashHardwareApi(value: characteristics, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct BleServicesDto: Hashable {
  var requestId: String
  var deviceId: String
  var services: [BleServiceDto]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> BleServicesDto? {
    let requestId = pigeonVar_list[0] as! String
    let deviceId = pigeonVar_list[1] as! String
    let services = pigeonVar_list[2] as! [BleServiceDto]

    return BleServicesDto(
      requestId: requestId,
      deviceId: deviceId,
      services: services
    )
  }
  func toList() -> [Any?] {
    return [
      requestId,
      deviceId,
      services,
    ]
  }
  static func == (lhs: BleServicesDto, rhs: BleServicesDto) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsHardwareApi(lhs.requestId, rhs.requestId) && deepEqualsHardwareApi(lhs.deviceId, rhs.deviceId) && deepEqualsHardwareApi(lhs.services, rhs.services)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("BleServicesDto")
    deepHashHardwareApi(value: requestId, hasher: &hasher)
    deepHashHardwareApi(value: deviceId, hasher: &hasher)
    deepHashHardwareApi(value: services, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct BleReadResultDto: Hashable {
  var requestId: String
  var deviceId: String
  var serviceUuid: String
  var characteristicUuid: String
  var payload: FlutterStandardTypedData


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> BleReadResultDto? {
    let requestId = pigeonVar_list[0] as! String
    let deviceId = pigeonVar_list[1] as! String
    let serviceUuid = pigeonVar_list[2] as! String
    let characteristicUuid = pigeonVar_list[3] as! String
    let payload = pigeonVar_list[4] as! FlutterStandardTypedData

    return BleReadResultDto(
      requestId: requestId,
      deviceId: deviceId,
      serviceUuid: serviceUuid,
      characteristicUuid: characteristicUuid,
      payload: payload
    )
  }
  func toList() -> [Any?] {
    return [
      requestId,
      deviceId,
      serviceUuid,
      characteristicUuid,
      payload,
    ]
  }
  static func == (lhs: BleReadResultDto, rhs: BleReadResultDto) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsHardwareApi(lhs.requestId, rhs.requestId) && deepEqualsHardwareApi(lhs.deviceId, rhs.deviceId) && deepEqualsHardwareApi(lhs.serviceUuid, rhs.serviceUuid) && deepEqualsHardwareApi(lhs.characteristicUuid, rhs.characteristicUuid) && deepEqualsHardwareApi(lhs.payload, rhs.payload)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("BleReadResultDto")
    deepHashHardwareApi(value: requestId, hasher: &hasher)
    deepHashHardwareApi(value: deviceId, hasher: &hasher)
    deepHashHardwareApi(value: serviceUuid, hasher: &hasher)
    deepHashHardwareApi(value: characteristicUuid, hasher: &hasher)
    deepHashHardwareApi(value: payload, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct BleWriteResultDto: Hashable {
  var requestId: String
  var deviceId: String
  var serviceUuid: String
  var characteristicUuid: String
  var accepted: Bool
  var nativeCode: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> BleWriteResultDto? {
    let requestId = pigeonVar_list[0] as! String
    let deviceId = pigeonVar_list[1] as! String
    let serviceUuid = pigeonVar_list[2] as! String
    let characteristicUuid = pigeonVar_list[3] as! String
    let accepted = pigeonVar_list[4] as! Bool
    let nativeCode: String? = nilOrValue(pigeonVar_list[5])

    return BleWriteResultDto(
      requestId: requestId,
      deviceId: deviceId,
      serviceUuid: serviceUuid,
      characteristicUuid: characteristicUuid,
      accepted: accepted,
      nativeCode: nativeCode
    )
  }
  func toList() -> [Any?] {
    return [
      requestId,
      deviceId,
      serviceUuid,
      characteristicUuid,
      accepted,
      nativeCode,
    ]
  }
  static func == (lhs: BleWriteResultDto, rhs: BleWriteResultDto) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsHardwareApi(lhs.requestId, rhs.requestId) && deepEqualsHardwareApi(lhs.deviceId, rhs.deviceId) && deepEqualsHardwareApi(lhs.serviceUuid, rhs.serviceUuid) && deepEqualsHardwareApi(lhs.characteristicUuid, rhs.characteristicUuid) && deepEqualsHardwareApi(lhs.accepted, rhs.accepted) && deepEqualsHardwareApi(lhs.nativeCode, rhs.nativeCode)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("BleWriteResultDto")
    deepHashHardwareApi(value: requestId, hasher: &hasher)
    deepHashHardwareApi(value: deviceId, hasher: &hasher)
    deepHashHardwareApi(value: serviceUuid, hasher: &hasher)
    deepHashHardwareApi(value: characteristicUuid, hasher: &hasher)
    deepHashHardwareApi(value: accepted, hasher: &hasher)
    deepHashHardwareApi(value: nativeCode, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct BleNotificationDto: Hashable {
  var requestId: String? = nil
  var deviceId: String
  var serviceUuid: String
  var characteristicUuid: String
  var payload: FlutterStandardTypedData
  var timestampMillis: Int64
  var sequenceNumber: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> BleNotificationDto? {
    let requestId: String? = nilOrValue(pigeonVar_list[0])
    let deviceId = pigeonVar_list[1] as! String
    let serviceUuid = pigeonVar_list[2] as! String
    let characteristicUuid = pigeonVar_list[3] as! String
    let payload = pigeonVar_list[4] as! FlutterStandardTypedData
    let timestampMillis = pigeonVar_list[5] as! Int64
    let sequenceNumber = pigeonVar_list[6] as! Int64

    return BleNotificationDto(
      requestId: requestId,
      deviceId: deviceId,
      serviceUuid: serviceUuid,
      characteristicUuid: characteristicUuid,
      payload: payload,
      timestampMillis: timestampMillis,
      sequenceNumber: sequenceNumber
    )
  }
  func toList() -> [Any?] {
    return [
      requestId,
      deviceId,
      serviceUuid,
      characteristicUuid,
      payload,
      timestampMillis,
      sequenceNumber,
    ]
  }
  static func == (lhs: BleNotificationDto, rhs: BleNotificationDto) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsHardwareApi(lhs.requestId, rhs.requestId) && deepEqualsHardwareApi(lhs.deviceId, rhs.deviceId) && deepEqualsHardwareApi(lhs.serviceUuid, rhs.serviceUuid) && deepEqualsHardwareApi(lhs.characteristicUuid, rhs.characteristicUuid) && deepEqualsHardwareApi(lhs.payload, rhs.payload) && deepEqualsHardwareApi(lhs.timestampMillis, rhs.timestampMillis) && deepEqualsHardwareApi(lhs.sequenceNumber, rhs.sequenceNumber)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("BleNotificationDto")
    deepHashHardwareApi(value: requestId, hasher: &hasher)
    deepHashHardwareApi(value: deviceId, hasher: &hasher)
    deepHashHardwareApi(value: serviceUuid, hasher: &hasher)
    deepHashHardwareApi(value: characteristicUuid, hasher: &hasher)
    deepHashHardwareApi(value: payload, hasher: &hasher)
    deepHashHardwareApi(value: timestampMillis, hasher: &hasher)
    deepHashHardwareApi(value: sequenceNumber, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct NativeErrorDto: Hashable {
  var code: String
  var domainCode: String
  var message: String? = nil
  var requestId: String? = nil
  var deviceId: String? = nil
  var retryable: Bool
  var timestampMillis: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativeErrorDto? {
    let code = pigeonVar_list[0] as! String
    let domainCode = pigeonVar_list[1] as! String
    let message: String? = nilOrValue(pigeonVar_list[2])
    let requestId: String? = nilOrValue(pigeonVar_list[3])
    let deviceId: String? = nilOrValue(pigeonVar_list[4])
    let retryable = pigeonVar_list[5] as! Bool
    let timestampMillis = pigeonVar_list[6] as! Int64

    return NativeErrorDto(
      code: code,
      domainCode: domainCode,
      message: message,
      requestId: requestId,
      deviceId: deviceId,
      retryable: retryable,
      timestampMillis: timestampMillis
    )
  }
  func toList() -> [Any?] {
    return [
      code,
      domainCode,
      message,
      requestId,
      deviceId,
      retryable,
      timestampMillis,
    ]
  }
  static func == (lhs: NativeErrorDto, rhs: NativeErrorDto) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsHardwareApi(lhs.code, rhs.code) && deepEqualsHardwareApi(lhs.domainCode, rhs.domainCode) && deepEqualsHardwareApi(lhs.message, rhs.message) && deepEqualsHardwareApi(lhs.requestId, rhs.requestId) && deepEqualsHardwareApi(lhs.deviceId, rhs.deviceId) && deepEqualsHardwareApi(lhs.retryable, rhs.retryable) && deepEqualsHardwareApi(lhs.timestampMillis, rhs.timestampMillis)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("NativeErrorDto")
    deepHashHardwareApi(value: code, hasher: &hasher)
    deepHashHardwareApi(value: domainCode, hasher: &hasher)
    deepHashHardwareApi(value: message, hasher: &hasher)
    deepHashHardwareApi(value: requestId, hasher: &hasher)
    deepHashHardwareApi(value: deviceId, hasher: &hasher)
    deepHashHardwareApi(value: retryable, hasher: &hasher)
    deepHashHardwareApi(value: timestampMillis, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct CommandResultDto: Hashable {
  var requestId: String
  var deviceId: String
  var accepted: Bool
  var nativeCode: String? = nil
  var domainCode: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> CommandResultDto? {
    let requestId = pigeonVar_list[0] as! String
    let deviceId = pigeonVar_list[1] as! String
    let accepted = pigeonVar_list[2] as! Bool
    let nativeCode: String? = nilOrValue(pigeonVar_list[3])
    let domainCode: String? = nilOrValue(pigeonVar_list[4])

    return CommandResultDto(
      requestId: requestId,
      deviceId: deviceId,
      accepted: accepted,
      nativeCode: nativeCode,
      domainCode: domainCode
    )
  }
  func toList() -> [Any?] {
    return [
      requestId,
      deviceId,
      accepted,
      nativeCode,
      domainCode,
    ]
  }
  static func == (lhs: CommandResultDto, rhs: CommandResultDto) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsHardwareApi(lhs.requestId, rhs.requestId) && deepEqualsHardwareApi(lhs.deviceId, rhs.deviceId) && deepEqualsHardwareApi(lhs.accepted, rhs.accepted) && deepEqualsHardwareApi(lhs.nativeCode, rhs.nativeCode) && deepEqualsHardwareApi(lhs.domainCode, rhs.domainCode)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("CommandResultDto")
    deepHashHardwareApi(value: requestId, hasher: &hasher)
    deepHashHardwareApi(value: deviceId, hasher: &hasher)
    deepHashHardwareApi(value: accepted, hasher: &hasher)
    deepHashHardwareApi(value: nativeCode, hasher: &hasher)
    deepHashHardwareApi(value: domainCode, hasher: &hasher)
  }
}

private class HardwareApiPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return PermissionKindDto(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return DoorCommandDto(rawValue: enumResultAsInt)
      }
      return nil
    case 131:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return BleConnectionStateDto(rawValue: enumResultAsInt)
      }
      return nil
    case 132:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return BleWriteTypeDto(rawValue: enumResultAsInt)
      }
      return nil
    case 133:
      return PermissionSnapshotDto.fromList(self.readValue() as! [Any?])
    case 134:
      return BleScanFilterDto.fromList(self.readValue() as! [Any?])
    case 135:
      return BleDeviceDto.fromList(self.readValue() as! [Any?])
    case 136:
      return BleConnectionEventDto.fromList(self.readValue() as! [Any?])
    case 137:
      return BleAuthenticationResultDto.fromList(self.readValue() as! [Any?])
    case 138:
      return WifiScanResultDto.fromList(self.readValue() as! [Any?])
    case 139:
      return WifiProvisionResultDto.fromList(self.readValue() as! [Any?])
    case 140:
      return BleCharacteristicDto.fromList(self.readValue() as! [Any?])
    case 141:
      return BleServiceDto.fromList(self.readValue() as! [Any?])
    case 142:
      return BleServicesDto.fromList(self.readValue() as! [Any?])
    case 143:
      return BleReadResultDto.fromList(self.readValue() as! [Any?])
    case 144:
      return BleWriteResultDto.fromList(self.readValue() as! [Any?])
    case 145:
      return BleNotificationDto.fromList(self.readValue() as! [Any?])
    case 146:
      return NativeErrorDto.fromList(self.readValue() as! [Any?])
    case 147:
      return CommandResultDto.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class HardwareApiPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? PermissionKindDto {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? DoorCommandDto {
      super.writeByte(130)
      super.writeValue(value.rawValue)
    } else if let value = value as? BleConnectionStateDto {
      super.writeByte(131)
      super.writeValue(value.rawValue)
    } else if let value = value as? BleWriteTypeDto {
      super.writeByte(132)
      super.writeValue(value.rawValue)
    } else if let value = value as? PermissionSnapshotDto {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else if let value = value as? BleScanFilterDto {
      super.writeByte(134)
      super.writeValue(value.toList())
    } else if let value = value as? BleDeviceDto {
      super.writeByte(135)
      super.writeValue(value.toList())
    } else if let value = value as? BleConnectionEventDto {
      super.writeByte(136)
      super.writeValue(value.toList())
    } else if let value = value as? BleAuthenticationResultDto {
      super.writeByte(137)
      super.writeValue(value.toList())
    } else if let value = value as? WifiScanResultDto {
      super.writeByte(138)
      super.writeValue(value.toList())
    } else if let value = value as? WifiProvisionResultDto {
      super.writeByte(139)
      super.writeValue(value.toList())
    } else if let value = value as? BleCharacteristicDto {
      super.writeByte(140)
      super.writeValue(value.toList())
    } else if let value = value as? BleServiceDto {
      super.writeByte(141)
      super.writeValue(value.toList())
    } else if let value = value as? BleServicesDto {
      super.writeByte(142)
      super.writeValue(value.toList())
    } else if let value = value as? BleReadResultDto {
      super.writeByte(143)
      super.writeValue(value.toList())
    } else if let value = value as? BleWriteResultDto {
      super.writeByte(144)
      super.writeValue(value.toList())
    } else if let value = value as? BleNotificationDto {
      super.writeByte(145)
      super.writeValue(value.toList())
    } else if let value = value as? NativeErrorDto {
      super.writeByte(146)
      super.writeValue(value.toList())
    } else if let value = value as? CommandResultDto {
      super.writeByte(147)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class HardwareApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return HardwareApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return HardwareApiPigeonCodecWriter(data: data)
  }
}

class HardwareApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = HardwareApiPigeonCodec(readerWriter: HardwareApiPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol HardwareHostApi {
  func getPermissionSnapshot() throws -> PermissionSnapshotDto
  func requestPermissions(permissions: [PermissionKindDto]) throws -> PermissionSnapshotDto
  func startBleScan(requestId: String, filter: BleScanFilterDto) throws
  func stopBleScan(requestId: String) throws
  func connectBleDevice(requestId: String, deviceId: String, completion: @escaping (Result<BleConnectionEventDto, Error>) -> Void)
  func authenticateBleDevice(requestId: String, deviceId: String, token: String, completion: @escaping (Result<BleAuthenticationResultDto, Error>) -> Void)
  func scanWifiNetworks(requestId: String, deviceId: String, completion: @escaping (Result<WifiScanResultDto, Error>) -> Void)
  func configureWifi(requestId: String, deviceId: String, ssid: String, password: String, completion: @escaping (Result<WifiProvisionResultDto, Error>) -> Void)
  func disconnectBleDevice(requestId: String, deviceId: String, completion: @escaping (Result<BleConnectionEventDto, Error>) -> Void)
  func discoverServices(requestId: String, deviceId: String, completion: @escaping (Result<BleServicesDto, Error>) -> Void)
  func readCharacteristic(requestId: String, deviceId: String, serviceUuid: String, characteristicUuid: String, completion: @escaping (Result<BleReadResultDto, Error>) -> Void)
  func writeCharacteristic(requestId: String, deviceId: String, serviceUuid: String, characteristicUuid: String, payload: FlutterStandardTypedData, writeType: BleWriteTypeDto, completion: @escaping (Result<BleWriteResultDto, Error>) -> Void)
  func setCharacteristicNotify(requestId: String, deviceId: String, serviceUuid: String, characteristicUuid: String, enabled: Bool, completion: @escaping (Result<BleWriteResultDto, Error>) -> Void)
  func sendDoorCommand(requestId: String, deviceId: String, command: DoorCommandDto) throws -> CommandResultDto
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class HardwareHostApiSetup {
  static var codec: FlutterStandardMessageCodec { HardwareApiPigeonCodec.shared }
  /// Sets up an instance of `HardwareHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: HardwareHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let getPermissionSnapshotChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flinx.HardwareHostApi.getPermissionSnapshot\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getPermissionSnapshotChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getPermissionSnapshot()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getPermissionSnapshotChannel.setMessageHandler(nil)
    }
    let requestPermissionsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flinx.HardwareHostApi.requestPermissions\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      requestPermissionsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let permissionsArg = args[0] as! [PermissionKindDto]
        do {
          let result = try api.requestPermissions(permissions: permissionsArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      requestPermissionsChannel.setMessageHandler(nil)
    }
    let startBleScanChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flinx.HardwareHostApi.startBleScan\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startBleScanChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestIdArg = args[0] as! String
        let filterArg = args[1] as! BleScanFilterDto
        do {
          try api.startBleScan(requestId: requestIdArg, filter: filterArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      startBleScanChannel.setMessageHandler(nil)
    }
    let stopBleScanChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flinx.HardwareHostApi.stopBleScan\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      stopBleScanChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestIdArg = args[0] as! String
        do {
          try api.stopBleScan(requestId: requestIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      stopBleScanChannel.setMessageHandler(nil)
    }
    let connectBleDeviceChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flinx.HardwareHostApi.connectBleDevice\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      connectBleDeviceChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestIdArg = args[0] as! String
        let deviceIdArg = args[1] as! String
        api.connectBleDevice(requestId: requestIdArg, deviceId: deviceIdArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      connectBleDeviceChannel.setMessageHandler(nil)
    }
    let authenticateBleDeviceChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flinx.HardwareHostApi.authenticateBleDevice\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      authenticateBleDeviceChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestIdArg = args[0] as! String
        let deviceIdArg = args[1] as! String
        let tokenArg = args[2] as! String
        api.authenticateBleDevice(requestId: requestIdArg, deviceId: deviceIdArg, token: tokenArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      authenticateBleDeviceChannel.setMessageHandler(nil)
    }
    let scanWifiNetworksChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flinx.HardwareHostApi.scanWifiNetworks\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      scanWifiNetworksChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestIdArg = args[0] as! String
        let deviceIdArg = args[1] as! String
        api.scanWifiNetworks(requestId: requestIdArg, deviceId: deviceIdArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      scanWifiNetworksChannel.setMessageHandler(nil)
    }
    let configureWifiChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flinx.HardwareHostApi.configureWifi\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      configureWifiChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestIdArg = args[0] as! String
        let deviceIdArg = args[1] as! String
        let ssidArg = args[2] as! String
        let passwordArg = args[3] as! String
        api.configureWifi(requestId: requestIdArg, deviceId: deviceIdArg, ssid: ssidArg, password: passwordArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      configureWifiChannel.setMessageHandler(nil)
    }
    let disconnectBleDeviceChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flinx.HardwareHostApi.disconnectBleDevice\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      disconnectBleDeviceChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestIdArg = args[0] as! String
        let deviceIdArg = args[1] as! String
        api.disconnectBleDevice(requestId: requestIdArg, deviceId: deviceIdArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      disconnectBleDeviceChannel.setMessageHandler(nil)
    }
    let discoverServicesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flinx.HardwareHostApi.discoverServices\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      discoverServicesChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestIdArg = args[0] as! String
        let deviceIdArg = args[1] as! String
        api.discoverServices(requestId: requestIdArg, deviceId: deviceIdArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      discoverServicesChannel.setMessageHandler(nil)
    }
    let readCharacteristicChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flinx.HardwareHostApi.readCharacteristic\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      readCharacteristicChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestIdArg = args[0] as! String
        let deviceIdArg = args[1] as! String
        let serviceUuidArg = args[2] as! String
        let characteristicUuidArg = args[3] as! String
        api.readCharacteristic(requestId: requestIdArg, deviceId: deviceIdArg, serviceUuid: serviceUuidArg, characteristicUuid: characteristicUuidArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      readCharacteristicChannel.setMessageHandler(nil)
    }
    let writeCharacteristicChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flinx.HardwareHostApi.writeCharacteristic\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      writeCharacteristicChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestIdArg = args[0] as! String
        let deviceIdArg = args[1] as! String
        let serviceUuidArg = args[2] as! String
        let characteristicUuidArg = args[3] as! String
        let payloadArg = args[4] as! FlutterStandardTypedData
        let writeTypeArg = args[5] as! BleWriteTypeDto
        api.writeCharacteristic(requestId: requestIdArg, deviceId: deviceIdArg, serviceUuid: serviceUuidArg, characteristicUuid: characteristicUuidArg, payload: payloadArg, writeType: writeTypeArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      writeCharacteristicChannel.setMessageHandler(nil)
    }
    let setCharacteristicNotifyChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flinx.HardwareHostApi.setCharacteristicNotify\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setCharacteristicNotifyChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestIdArg = args[0] as! String
        let deviceIdArg = args[1] as! String
        let serviceUuidArg = args[2] as! String
        let characteristicUuidArg = args[3] as! String
        let enabledArg = args[4] as! Bool
        api.setCharacteristicNotify(requestId: requestIdArg, deviceId: deviceIdArg, serviceUuid: serviceUuidArg, characteristicUuid: characteristicUuidArg, enabled: enabledArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      setCharacteristicNotifyChannel.setMessageHandler(nil)
    }
    let sendDoorCommandChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flinx.HardwareHostApi.sendDoorCommand\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      sendDoorCommandChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestIdArg = args[0] as! String
        let deviceIdArg = args[1] as! String
        let commandArg = args[2] as! DoorCommandDto
        do {
          let result = try api.sendDoorCommand(requestId: requestIdArg, deviceId: deviceIdArg, command: commandArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      sendDoorCommandChannel.setMessageHandler(nil)
    }
  }
}
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol HardwareFlutterApiProtocol {
  func onBleScanResult(device deviceArg: BleDeviceDto, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onBleConnectionChanged(event eventArg: BleConnectionEventDto, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onBleNotification(notification notificationArg: BleNotificationDto, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onNativeError(error errorArg: NativeErrorDto, completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class HardwareFlutterApi: HardwareFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: HardwareApiPigeonCodec {
    return HardwareApiPigeonCodec.shared
  }
  func onBleScanResult(device deviceArg: BleDeviceDto, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.flinx.HardwareFlutterApi.onBleScanResult\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([deviceArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onBleConnectionChanged(event eventArg: BleConnectionEventDto, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.flinx.HardwareFlutterApi.onBleConnectionChanged\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([eventArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onBleNotification(notification notificationArg: BleNotificationDto, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.flinx.HardwareFlutterApi.onBleNotification\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([notificationArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
  func onNativeError(error errorArg: NativeErrorDto, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.flinx.HardwareFlutterApi.onNativeError\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([errorArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
}
